### ISSUE TITLE
Where can I find the source of the script which generate the examples at: https://shaka-player-demo.appspot.com/demo  ?

### ISSUE THREAD

**Issue by ssaguiar** [shaka-project/shaka-packager#1002]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
Linux Ubuntu

## Issue and steps to reproduce the problem

**Packager Command**:

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
Generate the streams

What happens instead?
The script didn't work 

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

I wish to have access to the scripts source that generate the demos player m3u8 streams, at the demo page, so I can use the infos to make our stream work.

**Comment by joeyparrish** [comment]
We didn't originally script everything, but it was all generated with FFmpeg and Shaka Packager.  Some of it was edited by hand afterward, for example to combine multiple streams into a multiperiod one.

Recently, I started working on config files to regenerate all of those streams with Shaka Streamer: https://github.com/google/shaka-streamer

I would recommend you check that out.  When we are able to generate all of the Player demo content with Streamer, we plan to commit the Streamer config files to the Player repo.

Does this help?

**Comment by ssaguiar** [comment]
We also use ffmpeg to encode the streams.
After we try to use shaka packager but we could not make it work as expected (we use widevine to encrypt the streams).
As I saw the shaka player examples working very well, and saw that they use shaka packager I was wondering how they were encoded and if we could see the scripts used to do so.

Ths is part of the m3u8 of one of the demos:

.
.
```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.3.0-5bf8ad5-release
```
.
.

**Comment by joeyparrish** [comment]
I would advise that you either:

1. Try [Shaka Streamer](https://github.com/google/shaka-streamer), which will call FFmpeg and Packager for you in a way that we know to work well.  This is how some of Shaka Player's 1st-party demo content is generated, and how all of it will be generated in the near future. 
2. Or use the bug report template of Shaka Packager to share with us streams and exact Packager commands so that someone can help you debug the issue.

Thanks!

**Comment by ssaguiar** [comment]
Thank you for your help

I tried to run it but it seems to have some error or bug:

Tried this command, from the docs:

`python3 /usr/local/bin/shaka-streamer -i config_files/input_looped_file_config.yaml -p config_files/pipeline_live_config.yaml -c gs://my_gcs_bucket/folder/`

Got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/shaka-streamer", line 32, in <module>
    import streamer
  File "/usr/local/lib/python3.5/dist-packages/streamer/__init__.py", line 3, in <module>
    from . import controller_node
  File "/usr/local/lib/python3.5/dist-packages/streamer/controller_node.py", line 58
    self._temp_dir: str = tempfile.mkdtemp(
                  ^
SyntaxError: invalid syntax
```

Thank for any clue about this error.

**Comment by joeyparrish** [comment]
It appears that your Python version is out of date.  Python 3.5 reached end-of-life status more than a year ago, and our minimum required version for Shaka Streamer is Python 3.6, due in part to the type-annotation syntax shown in the traceback.

There are instructions here for updating Python on various versions of Ubuntu:

https://docs.python-guide.org/starting/install3/linux/

If you already have Python 3.6, you should be able to run `python3.6 /usr/local/bin/shaka-streamer` or install it with `python3.6 -m pip install --upgrade shaka-streamer shaka-streamer-binaries`.

**Comment by ssaguiar** [comment]
I got it to work but now I am stuck as I want to transcode a hls stream and don't find how to do it.
I am already capturing the stream from satellite decoder, the encoding it to hls.
This is being saved to local folder, with the main m3u8 file.
Can you help one more time, maybe pointing to some example (I could not find anything about this application in the examples folder).

Thank you very much again.
