### ISSUE TITLE
Changes in Shaka

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-packager#1024]
Hi everyone,

I want to share with you some changes that are coming to the Shaka family of projects.  This will be cross-posted to shaka-player-users, shaka-packager-users, and the GitHub Issues pages of all of our projects.

### Shaka is moving within Google

After 7.5 years of Shaka under Chrome/Widevine, the Shaka projects are moving.  The Cast team, who has been a primary user of Shaka Player within Google, will be taking over ownership of Shaka from Chrome/Widevine.  We look forward to a closer relationship with Cast!

### Seeking volunteer maintainers

We are now offering members of the Shaka community an opportunity to share in maintenance responsibilities, such as responding to issues, reviewing and merging PRs, and making releases.  We think this is long overdue, and will help all Shaka projects move forward more quickly.

If you would like to volunteer as a maintainer for one or more of the Shaka projects, please email me privately at joeyparrish@google.com.

### Infrastructure is moving to GitHub Actions

We are rewriting our internal tools and processes to make them more publicly accessible.  Having Google-only tools (and even some Google-only tests) has become a barrier for contributors and has slowed down our release timelines.  

We are migrating all testing, release, and deployment infrastructure to GitHub Actions, and improving access as much as possible.  All contributors will be able to run the same tests and get faster feedback, and all maintainers will be equally able to create releases and deploy demos and docs.

We will also start sending our own contributions through the public PR process, rather than using a private code review process for Googlers.

### Questions?

If you have any questions about these changes, please don't hesitate to ask!  You can email me privately at joeyparrish@google.com or ask publicly via the GitHub Issues pages for any of our projects.

https://github.com/google/shaka-packager
https://github.com/google/shaka-player
https://github.com/google/shaka-player-embedded
https://github.com/google/shaka-streamer

Joey, on behalf of the Shaka Team

**Comment by Canta** [comment]
Hi there.

I see a PR of mine is failing because of configuration issues in the new testing pipeline, unrelated to my code. I'm sure it's part of the migration efforts to github actions, so it will most likely fixed eventually. However, I'm not sure how should we collaborators deal with such issues.
Should we create other issues, talk about it here, or just wait for the thing to be fixed?

Thanks.

**Comment by jbree** [comment]
Any anticipated changes to the usage of the depot_tools build system?

**Comment by zdanek** [comment]
Mine PR is waiting over month. I see the problem now :)
Fingers crossed for good changes!

**Comment by adityapatadia** [comment]
Just realised that documentation is removed https://google.github.io/shaka-packager/html/documentation.html

Is there a plan to put it at a new place?

**Comment by yash1994** [comment]
Documentation has been moved to https://shaka-project.github.io/shaka-packager/html/

**Comment by joeyparrish** [comment]
Yes, and although GitHub will forward git clone, push, and pull requests from the old address to the new one, it won't forward the HTTP requests for the docs.  We apologize for the inconvenience!

**Comment by Brainiarc7** [comment]
Sign me up. Check your email.
