### ISSUE TITLE
DVB sub : out of memory error based on size issue

### ISSUE THREAD

**Issue by Romain-Bernier** [shaka-project/shaka-packager#1026]
## System info
**Operating System**: Debian 10.11
**Shaka Packager Version**: On master (commit e1b0c7c45431327fd3ce193514a5407d07b39b22)

## Issue and steps to reproduce the problem
Packager crash with out of memory error when processing dvbsub input with region size smaller than the region position.
For example :
region size : 156 x 97
region position : 882 x 931
display definition segment : 1920 x 1080

**Packager Command**: ./packager in=movie.ts,stream=text,format=ttml+mp4,output=movieout.mp4

Issue : Out of memory error:

[0131/152408:INFO:demuxer.cc(89)] Demuxer::Run() on file '/movie.ts'.
[0131/152408:INFO:demuxer.cc(155)] Initialize Demuxer for file '/movie.ts'.
[0131/152408:FATAL:memory_linux.cc(35)] Out of memory, size = 18446744073709551615
#0 0x5609781e2413 base::debug::StackTrace::StackTrace()
#1 0x560978197f31 logging::LogMessage::~LogMessage()
#2 0x56097819c8ca base::(anonymous namespace)::OnNoMemorySize()
#3 0x56097819c9c2 malloc
#4 0x7f66fb77dfd8 operator new()
#5 0x56097899e04d shaka::media::DvbImageBuilder::DvbImageBuilder()
#6 0x56097899cff3 _ZNSt4pairIKtN5shaka5media15DvbImageBuilderEEC1IJtEJLm0EEJPNS2_18DvbImageColorSpaceENS2_9RgbaColorEiiEJLm0ELm1ELm2ELm3EEEERSt5tupleIJDpT_EERS9_IJDpT1_EESt12_Index_tupleIJXspT0_EEESI_IJXspT2_EEE
#7 0x56097899cab5 _ZNSt4pairIKtN5shaka5media15DvbImageBuilderEEC1IJtEJPNS2_18DvbImageColorSpaceENS2_9RgbaColorEiiEEESt21piecewise_construct_tSt5tupleIJDpT_EESA_IJDpT0_EE
#8 0x56097899c4de _ZN9__gnu_cxx13new_allocatorINSt8__detail10_Hash_nodeISt4pairIKtN5shaka5media15DvbImageBuilderEELb0EEEE9constructIS8_JRKSt21piecewise_construct_tSt5tupleIJtEESF_IJPNS6_18DvbImageColorSpaceENS6_9RgbaColorEiiEEEEEvPT_DpOT0_
#9 0x56097899b8ae _ZNSt16allocator_traitsISaINSt8__detail10_Hash_nodeISt4pairIKtN5shaka5media15DvbImageBuilderEELb0EEEEE9constructIS7_JRKSt21piecewise_construct_tSt5tupleIJtEESF_IJPNS5_18DvbImageColorSpaceENS5_9RgbaColorEiiEEEEEvRS9_PT_DpOT0_
#10 0x56097899a883 _ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKtN5shaka5media15DvbImageBuilderEELb0EEEEE16_M_allocate_nodeIJRKSt21piecewise_construct_tSt5tupleIJtEESF_IJPNS5_18DvbImageColorSpaceENS5_9RgbaColorEiiEEEEEPS8_DpOT_
#11 0x5609789988d4 _ZNSt10_HashtableItSt4pairIKtN5shaka5media15DvbImageBuilderEESaIS5_ENSt8__detail10_Select1stESt8equal_toItESt4hashItENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE10_M_emplaceIJRKSt21piecewise_construct_tSt5tupleIJtEESN_IJPNS3_18DvbImageColorSpaceENS3_9RgbaColorEiiEEEEES0_INS7_14_Node_iteratorIS5_Lb0ELb0EEEbESt17integral_constantIbLb1EEDpOT_
#12 0x560978996208 _ZNSt10_HashtableItSt4pairIKtN5shaka5media15DvbImageBuilderEESaIS5_ENSt8__detail10_Select1stESt8equal_toItESt4hashItENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb0ELb0ELb1EEEE7emplaceIJRKSt21piecewise_construct_tSt5tupleIJtEESN_IJPNS3_18DvbImageColorSpaceENS3_9RgbaColorEiiEEEEES0_INS7_14_Node_iteratorIS5_Lb0ELb0EEEbEDpOT_
#13 0x5609789940e2 _ZNSt9__cxx199813unordered_mapItN5shaka5media15DvbImageBuilderESt4hashItESt8equal_toItESaISt4pairIKtS3_EEE7emplaceIJRKSt21piecewise_construct_tSt5tupleIJtEESH_IJPNS2_18DvbImageColorSpaceENS2_9RgbaColorEiiEEEEES8_INSt8__detail14_Node_iteratorISA_Lb0ELb0EEEbEDpOT_
#14 0x5609789922c1 _ZNSt7__debug13unordered_mapItN5shaka5media15DvbImageBuilderESt4hashItESt8equal_toItESaISt4pairIKtS3_EEE7emplaceIJRKSt21piecewise_construct_tSt5tupleIJtEESH_IJPNS2_18DvbImageColorSpaceENS2_9RgbaColorEiiEEEEES8_IN11__gnu_debug14_Safe_iteratorINSt8__detail14_Node_iteratorISA_Lb0ELb0EEESC_EEbEDpOT_
#15 0x56097898f9de shaka::media::SubtitleComposer::GetObjectImage()
#16 0x56097898a8f2 shaka::media::DvbSubParser::ParseObjectData()
#17 0x560978987471 shaka::media::DvbSubParser::Parse()
#18 0x56097896c8e1 shaka::media::mp2t::EsParserDvb::ParseInternal()
#19 0x56097896bddc shaka::media::mp2t::EsParserDvb::Parse()
#20 0x56097895e4c9 shaka::media::mp2t::TsSectionPes::ParseInternal()
#21 0x56097895c814 shaka::media::mp2t::TsSectionPes::Emit()
#22 0x56097895c4ca shaka::media::mp2t::TsSectionPes::Parse()
#23 0x5609789487c8 shaka::media::mp2t::PidState::PushTsPacket()
#24 0x560978949ac1 shaka::media::mp2t::Mp2tMediaParser::Parse()
#25 0x56097893dc42 shaka::media::Demuxer::Parse()
#26 0x56097893b063 shaka::media::Demuxer::Run()
#27 0x56097836c1db shaka::media::Job::Run()
#28 0x5609782bc0ee base::SimpleThread::ThreadMain()
#29 0x5609781cbad3 base::(anonymous namespace)::ThreadFunc()
#30 0x7f66fb532fa3 start_thread
#31 0x7f66fb4634cf clone

[1]    21053 abort      ./packager

Extra steps to reproduce the problem? No

What is the expected result? No error :) 

What happens instead? 
Based on my investigations the out of memory error come from the creation of the `RgbaColor` struct with the `max_width` and `max_height` generated by the `SubtitleComposer::GetObjectImage` with the following code :
 ```
 info->second.region->width - info->second.region->x,
 info->second.region->height - info->second.region->y
 ```
 I don't understand why this subtraction is performed, I will do the following instead : 
 ```
display_width_ - info->second.region->x,
display_height_ - info->second.region->y
 ```
 
I would highly appreciate if you take the time to explain this subtraction for me.
Thanks

**Comment by Brainiarc7** [comment]
This is probably related to #903

**Comment by cosmin** [comment]
Related to #1195
