### ISSUE TITLE
What is the format of the time displayed by $Time$ of segment template formatting

### ISSUE THREAD

**Issue by jbuduoo** [shaka-project/shaka-packager#1041]
## System info
Operating System:Rocky-8.4-x86_64
Shaka Packager Version: v2.6.1

## Issue and steps to reproduce the problem

「1576576241」Doesn't look like a Unix timestamp either.
Excuse me, what kind of time format is this.

![](https://i.imgur.com/FzGAWzu.png)
## documents:
![](https://i.imgur.com/0uRdyR7.png)

## code snippet:
/opt/asorigin/web/bin/packager 
'in=udp://224.1.1.1:5001?reuse=1,stream=0,init_segment=/opt/asorigin/content/vod/nfs/s01/a04/audio/5001/init_0.m4s,segment_template=/opt/asorigin/content/vod/nfs/s01/a04/audio/5001/0_$Time$.m4s,language=zho' \
'in=udp://224.1.1.1:5002?reuse=1,stream=video,init_segment=/opt/asorigin/content/vod/nfs/s01/a04/video/5002/init_1.m4s,segment_template=/opt/asorigin/content/vod/nfs/s01/a04/video/5002/1_$Time$.m4s' \
--segment_duration 4 \
--fragment_duration 4 \
--preserved_segments_outside_live_window 15 \
--time_shift_buffer_depth 60 \
--mpd_output '/opt/asorigin/content/vod/nfs/s01/a04/index.mpd'

## Displayed filename:
![](https://i.imgur.com/eaOQLnv.png)

**Comment by joeyparrish** [comment]
The `$Time$` parameter is spec'd (in DASH) to be in timescale units.  For example, if your timescale is 90000, then a timestamp of 8675309 would correspond to 96.392 seconds.

**Comment by jbuduoo** [comment]
The last 5 codes are ms or µs.
The first 5 yards are seconds.
Divide the number of seconds by 60 and then by 60 to get the current time.
ex:74095/60/60
=20.58 hours

**Comment by joeyparrish** [comment]
@jbuduoo, that doesn't seem right.  What are you basing that on?
