### ISSUE TITLE
Tutorial and Documentation link inside readme.md not working

### ISSUE THREAD

**Issue by aliasgar55** [shaka-project/shaka-packager#1043]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

Tutorial and documentation link not working in Readme.md

## Issue and steps to reproduce the problem
In the readme.md  under the  **Useful Link** header
Click on Documentation 
Click on Tutorial

What is the expected result?
Must open Documentation and tutorial page in new tab respectively.

What happens instead?
Return 404 error code

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by joeyparrish** [comment]
Understood.  This is resolved by PR #1042.
