### ISSUE TITLE
Does shaka currently provide conversion of h265 4k video, or suggest me what method to use to convert h265 4k format.

### ISSUE THREAD

**Issue by jbuduoo** [shaka-project/shaka-packager#1052]
## System info
**Operating System**: Rocky-8.4-x86_64
**Shaka Packager Version**: v2.6.1

## Issue and steps to reproduce the problem
Does shaka currently provide conversion of h265 4k video, or suggest me what method to use to convert h265 4k format.

**Comment by jbuduoo** [comment]
I correct my question:
Shaka Packager unable to pack H265 4K videos.

Code:
/opt/asorigin/web/bin/packager \
'in=udp://224.1.1.2:5001?reuse=1,stream=video,init_segment=/opt/asorigin/content/vod/nfs/s02/a05/video/224.1.1.2:5001/init_0.mp4,segment_template=/opt/asorigin/content/vod/nfs/s02/a05/video/224.1.1.2:5001/video_0_$Number$.mp4,playlist_name=/opt/asorigin/content/vod/nfs/s02/a05/video/224.1.1.2:5001/video_0.m3u8,drm_label=HD' --default_language chi --segment_duration 4 --fragment_duration 4 --preserved_segments_outside_live_window 15 --time_shift_buffer_depth 60 --hls_master_playlist_output '/opt/asorigin/content/vod/nfs/s02/a05/index.m3u8' --hls_playlist_type LIVE

Error message:
[0325/110417:ERROR:packager_main.cc(554)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file udp://224.1.1.2:5001?reuse=1

How to deal with it?

**Comment by joeyparrish** [comment]
H265 parsing and packaging is supported.  You may have an issue with the format of what you're pushing into the UDP pipe.

What container format are you streaming over UDP?

**Comment by jbuduoo** [comment]
I used --dump_stream_info and mediaInfo to query the video data

## /opt/asorigin/web/bin/packager 'in=udp://224.1.1.2:5001?reuse=1' --dump_stream_info
![](https://i.imgur.com/sFlPLeN.png)

## Information queried using mediaInfo
![](https://i.imgur.com/kW1fvJ4.png)
![](https://i.imgur.com/mt409uw.png)

**Comment by joeyparrish** [comment]
Okay, so it's TS packets over UDP.  What tool is generating them?  Is there a 1-to-1 match between TS packets and UDP packets?  Is there a possibility of packet loss between the two systems?

**Comment by jbuduoo** [comment]
I use winSend to transmit UDP, but to avoid loss, I read directly.

H265_4k The video download link is as follows:
https://drive.google.com/file/d/1Sl66RyTJlhY0Q4donxEFBBWR5OUxXBs-/view?usp=sharing

[root@localhost aaa]# /opt/asorigin/web/bin/packager \
> 'in=/opt/mv/h265_4k.ts,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.mp4' \
> 'in=/opt/mv/h265_4k.ts,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$Number$.mp4' \
> --segment_duration 20 \
> --mpd_output h264.mpd

[0401/063645:INFO:demuxer.cc(89)] Demuxer::Run() on file '/opt/mv/h265_4k.ts'.
[0401/063645:INFO:demuxer.cc(155)] Initialize Demuxer for file '/opt/mv/h265_4k.ts'.
[0401/063645:ERROR:mp2t_media_parser.cc(117)] Parsing failed for pid = 100, type=3
[0401/063645:ERROR:packager_main.cc(554)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file /opt/mv/h265_4k.ts


The error still exists, is there any other way?


In addition, I don't know where to look at the log records, and where the level of log records can be set. You can give me the corresponding keywords or web page links, so that I can have relevant knowledge.

**Comment by kqyang** [comment]
You can set the logging level by appending `--v=4` to your command, e.g.

```
[root@localhost aaa]# /opt/asorigin/web/bin/packager \
   'in=/opt/mv/h265_4k.ts,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.mp4' \
   ...
   --mpd_output h264.mpd  \
   --v=4
```

**Comment by jbuduoo** [comment]
Answered some of my questions.
I'll try to find the answer again, and if I can find it, I'll post it, if I can't find it, I'll close the question in a few days.

**Comment by joeyparrish** [comment]
Okay, thanks.  Let us know how it turns out.
