### ISSUE TITLE
Fairplay DRM playback error

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-packager#1053]
## System info
**Operating System**: macOS BigSur
**Shaka Packager Version**: 2.6.1

## Issue and steps to reproduce the problem
OS: macOS BigSur
Safari Browser Version: Version 14.0.3 (16610.4.3.1.4)

Issue: Not able to play the videos of 240p resolutions that are packaged by shaka-packager. We are using CBCS encryption scheme and packaging the video for both DASH and HLS. We are using widevine, playready and fairplay DRM. DASH video can be played with widevine in windows-chrome and also mac-chrome. But when we play the fairplay video shaka-player and also axinom-player gives playback error. This happens in only BigSur-fairplay-safari and for 240p resolutions only. Higher resolutions like 360p, 480p, 720p etc works fine.

## 240p video packaged with shaka-packager(This has issue in BigSur-fairplay-safari)
Input video: https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/input/240pVideo.mp4
Input audio: https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/input/240pAudio.mp4

Packager command:

./packager-linux-x64 in=240pVideo.mp4,stream=video,out=out/240pVideoPackaged.mp4,playlist_name=out/Stream_Video.m3u8 in=240pAudio.mp4,stream=audio,out=out/240pAudioPackaged.mp4,playlist_name=out/Stream_Audio.m3u8 --enable_raw_key_encryption --protection_systems Widevine,PlayReady,Fairplay --protection_scheme cbcs --keys label=:key_id=fcabef00000000000110750100119920:key=326264633530646333316a6a6a6a6a6a --segment_duration 4 --fragment_duration 4 --generate_static_live_mpd --mpd_output out/stream.mpd --hls_master_playlist_output out/stream.m3u8 --hls_key_uri skd://fcabef00-0000-0000-0110-750100119920:17395700000000000110750100119920 --iv 17395700000000000110750100119920

Output of above packager command:
https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/packaged/240p/stream.m3u8
https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/packaged/240p/stream.mpd

Play the video using axinom-player (Open the link in safari-bigsur, gives playback error):
https://vtb.axinom.com/fairplay_streaming_sample_player.html?url=https%3A%2F%2Fshaka-packager-debug.s3.ap-south-1.amazonaws.com%2Fpackaged%2F240p%2Fstream.m3u8&license=https%3A%2F%2Fdrm-fairplay-licensing.axprod.net%2FAcquireLicense&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiNTIxZWU5NWQtOTUxMi00ZmE2LTk3NmEtYWQ4ZjAwZDdiNDQzIiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsInZlcnNpb24iOjIsImxpY2Vuc2UiOnsiZXhwaXJhdGlvbl9kYXRldGltZSI6IjIwMjItMDUtMDNUMDA6MDA6MDAuMDAwWiIsImFsbG93X3BlcnNpc3RlbmNlIjp0cnVlfSwiY29udGVudF9rZXlzX3NvdXJjZSI6eyJpbmxpbmUiOlt7ImlkIjoiZmNhYmVmMDAtMDAwMC0wMDAwLTAxMTAtNzUwMTAwMTE5OTIwIiwiZW5jcnlwdGVkX2tleSI6InhndXlncytSUHZNRjhPWXU4N25Fcnc9PSIsInVzYWdlX3BvbGljeSI6IkxzdFBvbGljeSIsIml2IjoiRnpsWEFBQUFBQUFCRUhVQkFCR1pJQT09In1dfSwiY29udGVudF9rZXlfdXNhZ2VfcG9saWNpZXMiOlt7Im5hbWUiOiJMc3RQb2xpY3kifV0sImxpY2Vuc2Vfc2VydmVyIjp7InJldHVybl9saWNlbnNlX3JlcXVlc3RfaW5mbyI6dHJ1ZX19LCJiZWdpbl9kYXRlIjoiMjAyMi0wMy0zMVQwNDoyMzozNC4yMDlaIiwiZXhwaXJhdGlvbl9kYXRlIjoiMjAyNC0xMi0yNlQwNDoyMzozNC4yMDlaIn0.j0kwxlWYkwh1662C54UKk3XCF_yRNNwi12Z_JtDs6g8&certUrl=https%3A%2F%2Ffps-certs.learnyst.com%2Ftestcert%2Ffairplay.cer

Using shaka player also the playback fails with the below exception:
{\"severity\":2,\"category\":3,\"code\":3016,\"data\":[3,null,null],\"handled\":false}"
3016-> The video element reported an error.error.data[0] is a MediaError code from the video element
data[0]=3-> Errors parsing or processing audio or video streams

## Higher resolution video packaged with shaka-packager(This works fine in BigSur-fairplay-safari)
Input video: https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/input/HighQualityVideo.mp4
Input audio: https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/input/HighQualityAudio.mp4

Packager command:
./packager-linux-x64 in=HighQualityVideo.mp4,stream=video,out=out/HighQualityVideoPackaged.mp4,playlist_name=out/Stream_Video.m3u8 in=HighQualityAudio.mp4,stream=audio,out=out/HighQualityAudioPackaged.mp4,playlist_name=out/Stream_Audio.m3u8 --enable_raw_key_encryption --protection_systems Widevine,PlayReady,Fairplay --protection_scheme cbcs --keys label=:key_id=fcabef00000000000110750100119920:key=326264633530646333316a6a6a6a6a6a --segment_duration 4 --fragment_duration 4 --generate_static_live_mpd --mpd_output out/stream.mpd --hls_master_playlist_output out/stream.m3u8 --hls_key_uri skd://fcabef00-0000-0000-0110-750100119920:17395700000000000110750100119920 --iv 17395700000000000110750100119920

Output of above packager command:
https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/packaged/HighQuality/stream.m3u8
https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/packaged/HighQuality/stream.mpd

Play the video using axinom-player (Works in DASH/widevine, HLS/fairplay-bigsur-safar, open below link in bigsur-safarii):
https://vtb.axinom.com/fairplay_streaming_sample_player.html?url=https%3A%2F%2Fshaka-packager-debug.s3.ap-south-1.amazonaws.com%2Fpackaged%2FHighQuality%2Fstream.m3u8&license=https%3A%2F%2Fdrm-fairplay-licensing.axprod.net%2FAcquireLicense&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiNTIxZWU5NWQtOTUxMi00ZmE2LTk3NmEtYWQ4ZjAwZDdiNDQzIiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsInZlcnNpb24iOjIsImxpY2Vuc2UiOnsiZXhwaXJhdGlvbl9kYXRldGltZSI6IjIwMjItMDUtMDNUMDA6MDA6MDAuMDAwWiIsImFsbG93X3BlcnNpc3RlbmNlIjp0cnVlfSwiY29udGVudF9rZXlzX3NvdXJjZSI6eyJpbmxpbmUiOlt7ImlkIjoiZmNhYmVmMDAtMDAwMC0wMDAwLTAxMTAtNzUwMTAwMTE5OTIwIiwiZW5jcnlwdGVkX2tleSI6InhndXlncytSUHZNRjhPWXU4N25Fcnc9PSIsInVzYWdlX3BvbGljeSI6IkxzdFBvbGljeSIsIml2IjoiRnpsWEFBQUFBQUFCRUhVQkFCR1pJQT09In1dfSwiY29udGVudF9rZXlfdXNhZ2VfcG9saWNpZXMiOlt7Im5hbWUiOiJMc3RQb2xpY3kifV0sImxpY2Vuc2Vfc2VydmVyIjp7InJldHVybl9saWNlbnNlX3JlcXVlc3RfaW5mbyI6dHJ1ZX19LCJiZWdpbl9kYXRlIjoiMjAyMi0wMy0zMVQwNDoyMzozNC4yMDlaIiwiZXhwaXJhdGlvbl9kYXRlIjoiMjAyNC0xMi0yNlQwNDoyMzozNC4yMDlaIn0.j0kwxlWYkwh1662C54UKk3XCF_yRNNwi12Z_JtDs6g8&certUrl=https%3A%2F%2Ffps-certs.learnyst.com%2Ftestcert%2Ffairplay.cer

## 240p video packaged with axinom-packager(This works fine in BigSur-fairplay-safari, open below link is bigsur safari)
I dont have the commands for axinom packager. Axinom team has prepared the content for the same 240p video.

https://vtb.axinom.com/fairplay_streaming_sample_player.html?url=https%3A%2F%2Faxinoms3bucket-nimasha.s3.us-east-2.amazonaws.com%2Foutput%2Fcmaf%2Fmanifest.m3u8&license=https%3A%2F%2Fdrm-fairplay-licensing.axtest.net%2FAcquireLicense&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjogMSwKImJlZ2luX2RhdGUiOiAiMjAwMC0wMS0wMVQxMjoyODozNSswMzowMCIsCiJleHBpcmF0aW9uX2RhdGUiOiAiMjAyNS0xMi0zMVQyMzo1OTo0MCswMzowMCIsCiJjb21fa2V5X2lkIjogIjE3ZTIzYmFmLTZkYWYtNGYyOS1hZTRjLWFkODMwMGJiOWMwNCIsCiJtZXNzYWdlIjogewogICJ0eXBlIjogImVudGl0bGVtZW50X21lc3NhZ2UiLAogICJ2ZXJzaW9uIjogMiwKICAibGljZW5zZSI6IHsKICAgICJkdXJhdGlvbiI6IDM2MDAwCiAgfSwKICAiY29udGVudF9rZXlzX3NvdXJjZSI6IHsKICAgICJpbmxpbmUiOiBbCiAgICAgIHsKICAgICAgICAiaWQiOiAiNzY5NGY4YjctOTMyZS00Mzg2LTgxMjktZjlkMTdkY2ZmZjBmIgogICAgICB9CiAgICBdCiAgfQp9fQ.7B0WTjy13wwZaAiAsPwaGTOhEZTmDQswICOqUtv5WDo&certUrl=https%3A%2F%2Fvtb.axinom.com%2FFPScert%2Ffairplay.cer

Extra steps to reproduce the problem?
(1) Just open the above player links in safari-bigsur

What is the expected result?
Playback should be success for 240p resolution in bigsur-fairplay-safari

What happens instead?
playback fails in shaka-player, axinom-player. happens only for 240p videos. Happens in bigsur. **Works in mac-os monterey**

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by sridhard** [comment]
Any update on this issue

**Comment by SeawardT** [comment]
I just want to confirm that the 240p issue works on the latest Monterey (12.3.1), but fails only on BigSur (11.6.5)? If you are using any other version to verify this, please let me know.

**Comment by sridhard** [comment]
@SeawardT dorry for the late reply. I am using BigSur(11.2.2). In BigSur(11.2.2) it is failing. 

Are you able to reproduce this issue?
