### ISSUE TITLE
"Box xxx is too large" while packaging VOD HLS stream on 32-bit OS Odroid XU4

### ISSUE THREAD

**Issue by kgrze** [shaka-project/shaka-packager#1058]
I have cross-compiled shaka-packager v2.6.1 for armhf to run it on Odroid XU4 with Ubuntu 20.04 LTS.
Packager runs correcty however when I wanted to produce HLS stream from MP4 file I have observed packaging error:

ERROR:box_reader.cc(143)] Box 'F`詰' size (3040042991) is too large.

When I compiled the same code for amd64 and run it on my laptop with Ubuntu 20.04, the issue doesn't exist.

I suspect that the error I am seeing is connected with Odroid XU4 board which is armv7 32-bit OS. On 64-bit OS the issue doesn't appear.

What can be done to fix this issue?

**Comment by cosmin** [comment]
32-bit operating systems are not supported and we don't have plans to support it.
