### ISSUE TITLE
Video is not getting played in Safari

### ISSUE THREAD

**Issue by KVPasupuleti** [shaka-project/shaka-packager#1059]
## System info
**Operating System**: macOS Big Sur, mac M1
**Shaka Packager Version**: 3fd538a587-release

## Issue and steps to reproduce the problem

We have generated a HLS manifest using Shaka packager. It played fine in Chrome, but is behaving weirdly in Mac Safari.

These are the player specific behaviours:

- In Shaka player demo, the playback is not even getting started and the player is in a continuous loading state with a loader on the first frame.
- In other demo players like Bitmovin player, the video is playing frame by frame in a very slow motion (Obviously, the audio manifest is not downloaded here too)

These are the data points I observed.

1. The master manifest is fetched twice where the second fetch is getting failed.
2. The video manifest is fetched fine.
3. The audio manifest is not getting fetched.
4. Unlike in Chrome, the video segments are requested in multiple Byte-sized requests with the Range header added to the segment requests.
5. Some video segments are getting failed and retried twice or thrice.

**Packager Command**:

```
packager \
 'in=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/long_break/part_1.mp4,stream=audio,segment_template=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/v13_input/long_break/part_1/video128kbps_aac_$Number%09d$.ts,playlist_name=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/v13_input/long_break/part_1/video128kbps_aac.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
 'in=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/long_break/part_1.mp4,stream=video,segment_template=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/v13_input/long_break/part_1/video720_cmaf_$Number%09d$.ts,playlist_name=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/v13_input/long_break/part_1/video720_cmaf.m3u8,iframe_playlist_name=/home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/v13_input/long_break/part_1/video720_iframe.m3u8' \
--hls_master_playlist_output /home/ib-developer/Desktop/repositories/LearningPlatform/personalization_video_generation_utils/shaka/v13_input/long_break/part_1/video.m3u8 --segment_duration 3 --fragment_duration 3 --segment_template_constant_duration
```

Extra steps to reproduce the problem?
(1) For testing in Bitmovin player - Open [this](https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Ftesting-video-player.s3.ap-south-1.amazonaws.com%2FPersonalizedV2Testing%2Fshaka%2Fhls_v8%2Fuser_1_video.m3u8) link
(2) For testing in Shaka player - Open [this](https://shaka-player-demo.appspot.com/demo/#audiolang=en-IN;textlang=en-IN;uilang=en-IN;asset=https://testing-video-player.s3.ap-south-1.amazonaws.com/PersonalizedV2Testing/shaka/hls_v8/user_1_video.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled) link 

What is the expected result?

The video should play fine along with audio without any additional buffering.

What happens instead?

In Safari,

- The playback is not getting started in Shaka demo. 
- The video is playing frame wise in a slow motion without audio in Bitmovin demo.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

Attachment sent in mail from pasupuletikrishnavamsi@gmail.com

**Comment by KVPasupuleti** [comment]
I think I have figured it out. I have added discontinuities with a different codec string. 

If I use the segments with the same codec strings, it's working fine.

**Comment by cosmin** [comment]
There seems to be some command line parsing issue because the master playlist contains the following

```
URI="iframe.m3u8 --segment_template_constant_duration"
```

**Comment by cosmin** [comment]
I cannot reproduce the m3u8 file contents with the command line you supplied.
