### ISSUE TITLE
Error when parsing h265 Filler data followed by End of bitstream

### ISSUE THREAD

**Issue by akkermansadriaan** [shaka-project/shaka-packager#1063]
## System info
**Operating System**: macOS Monterey
**Shaka Packager Version**: v2.6.1-634af65-release

## Issue and steps to reproduce the problem
Our encoders produce h265/HEVC in a transport stream over UDP and this results in an error on Shaka Packager once in a while. I noticed it happens more specifically when `Filler data (0x26)` is followed by an `End of bitstream (0x25)`. 

**Packager Command**: 
```
packager
  'in=input.ts, stream=video, init_segment=video/init.mp4, playlist_name=video/main.m3u8'
  --mpd_output manifest.mpd
  --generate_static_live_mpd
  --hls_master_playlist_output master.m3u8
  --hls_playlist_type VOD
```

What happens instead?
```
[0607/163821:ERROR:h26x_byte_to_unit_stream_converter.cc(62)] H.26x byte stream frame did not begin with start code.
[0607/163821:ERROR:mp2t_media_parser.cc(117)] Parsing failed for pid = 101, type=3
```
I don't seem to be able to get packager to output more logging.

**Comment by cosmin** [comment]
Can you share a file to reproduce this problem?
