### ISSUE TITLE
How to have an Audio-Only Variant Stream ouput

### ISSUE THREAD

**Issue by xavierlaffargue** [shaka-project/shaka-packager#1065]
## System info
**Operating System**: All
**Shaka Packager Version**: 2.6.1

## Issue and steps to reproduce the problem

**Packager Command**:
`in=input.mp4,stream=0,out=out.aac --segment_duration 4 --hls_master_playlist_output master.m3u8`

**Result :**
master.m3u8

```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release

#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_0.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=128318,AVERAGE-BANDWIDTH=128209,CODECS="mp4a.40.2",AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_0.m3u8
```

**Question :**
I would like to know if an option "Audio Only Variant stream" (like on Elemental) exist !
I don't want several variants, I only want 1
the master manifest would give this : 

```
#EXTM3U

#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=128318,AVERAGE-BANDWIDTH=128209,CODECS="mp4a.40.2"
stream_0.m3u8
```

**Comment by xavierlaffargue** [comment]
Maybe @joeyparrish do you know the answer?

**Comment by cosmin** [comment]
Currently it's not possible, because `--hls_master_playlist_output` is required to enable HLS output.
