### ISSUE TITLE
cmaf multi drm content with Dolby atmos audio is not playing in ios devices

### ISSUE THREAD

**Issue by ashiskumarsahu** [shaka-project/shaka-packager#1070]
## System info
**Operating System**: All iOS
**Shaka Packager Version**:  v2.6.1-634af65-release

## Issue and steps to reproduce the problem

**Packager Command**:
./shakapackager \
  in=AC4.mp4,stream=audio,init_segment=output/audio/ac4/init.mp4,playlist_name=output/audio/ac4/stream.m3u8,segment_template='output/audio/ac4/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO  \
  in=EC3JOG.mp4,stream=audio,init_segment=output/audio/ec3jog/init.mp4,playlist_name=output/audio/ec3jog/stream.m3u8,segment_template='output/audio/ec3jog/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO \
  in=EC3.mp4,stream=audio,init_segment=output/audio/ec3/init.mp4,playlist_name=output/audio/ec3/stream.m3u8,segment_template='output/audio/ec3/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO \
  in=AAC.mp4,stream=audio,init_segment=output/audio/aac/init.mp4,playlist_name=output/audio/aac/stream.m3u8,segment_template='output/audio/aac/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO  \
  in=240_out.mp4,stream=video,init_segment='output/240/init.mp4',playlist_name=output/240/stream.m3u8,iframe_playlist_name=output/240/iframe.m3u8,segment_template='output/240/segment_$Number$.m4s',drm_label=SD \
  in=480_out.mp4,stream=video,init_segment='output/480/init.mp4',playlist_name=output/480/stream.m3u8,iframe_playlist_name=output/480/iframe.m3u8,segment_template='output/480/segment_$Number$.m4s',drm_label=SD \
  --segment_duration 10 \
  --protection_systems Widevine,PlayReady,FairPlay  \
  --protection_scheme cbcs \
  --enable_raw_key_encryption  \
  --keys label=AUDIO:key_id=xxxx:key=xxxx:iv=xxxx,label=SD:key_id=xxxx:key=xxxx:iv=xxxx \
  --hls_key_uri skd://sample_token \
  --generate_static_live_mpd --mpd_output output/stream.mpd  \
  --hls_master_playlist_output output/master.m3u8

Extra steps to reproduce the problem?
(1) Pack a cmaf multi drm content by adding a dolby atmos audio track
(2) After packaging try to play in ios devices. We have used a drm provider to genertate fairplay license token

What is the expected result?
It should play in all devices.

What happens instead?
Not playing in ios devices, some LG/Samsung TV apps and in lower version of fire TV.

As per our DRM provider cmaf should support in almost all devices. I have attached the screenshot regarding cmaf support provided from drm provider.

Thank You

![FireShot Capture 014 - Supported Environments - PallyCon Docs Home - pallycon com](https://user-images.githubusercontent.com/12328179/176127112-029d25b8-ef01-48a0-bd1e-e1b7e696e380.png)

**Comment by cosmin** [comment]
I don't believe AC4 is natively supported on iOS at this time per https://professionalsupport.dolby.com/s/article/Dolby-Audio-for-Applications-integration-in-iOS?language=en_US

If this works when you drop the Dolby Atmos audio track then it's safe to assume the CMAF and DRM integration is working and the codec is the issue. If it's still not working after dropping Dolby Atmos then there's probably an issue on the DRM side.
