### ISSUE TITLE
Question: Can I use Shaka-Packages with segmented m4s files?

### ISSUE THREAD

**Issue by venomone** [shaka-project/shaka-packager#1075]
Hey folks, 

I'm currently in a situation where I have a HLS structure outputted by ffmpeg. Basically this is a HLS ABR stream with multiple languages
and subtitles. Now I wanted to pack this stuff with Shaka packager (Widevine and Fairplay compatible) but I'm not sure how to properly do this as all examples I've found so far don't really match the structure of a HLS stream that I have.

To give you an example, how my folders are structured:

root folder:
![root](https://user-images.githubusercontent.com/43114687/180004370-622841e9-f5e2-4334-b389-da0d37ebd05d.png)

And inside each folder I have this:

![sub](https://user-images.githubusercontent.com/43114687/180004441-b768ee32-4d4e-452e-8a01-21c1864fa16b.png)

What do I know have to tell Shaka-Packager in order to encrypt my files?

**Comment by sr1990** [comment]
Hi @venomone 
Why are you not using shaka packager to create HLS content?
If you have not packaged the content yourself and want to encrypt it as hls/dash, 
just go in each folder and create full mp4 files by concatenating init file with m4s files sequentially (full_mp4_file = init + seg 1 + seg 2 + .... + seg n.)
and run shaka packager on them. 
Check out: https://shaka-project.github.io/shaka-packager/html/tutorials/hls.html#examples
