### ISSUE TITLE
[Docker Hub] Can someone help release the latest version to Docker Hub

### ISSUE THREAD

**Issue by unext-wendong** [shaka-project/shaka-packager#1077]
The current latest image on Docker Hub is `v2.5.1`, which is about one year old. Can someone help to push version `v2.6.1` there?

It seems to be enough to just trigger the Action `Docker Hub Release` from tag `v2.6.1`.

**Comment by unext-wendong** [comment]
FYI: The docker build seems to be failing on tag `v2.6.1`.
After porting the changes in file `./Dockerfile` from the latest commit in `main` (commit 31129eed64) to `v2.6.1`, the build succeeded, however, the generated image was still missing one package `c-ares`.

The latest `./Dockerfile` in `main` (commit 31129eed64) with the following change seems to generate a working image.
```
 # Copy only result binaries to our final image.
 FROM alpine:3.11
-RUN apk add --no-cache libstdc++ python
+RUN apk add --no-cache libstdc++ python c-ares
 COPY --from=builder /shaka_packager/src/out/Release/packager \
                     /shaka_packager/src/out/Release/mpd_generator \
                     /shaka_packager/src/out/Release/pssh-box.py \
```

**Comment by cosmin** [comment]
latest tag 3.0.4 is on docker hub.
