### ISSUE TITLE
xHE-AAC Audio Support

### ISSUE THREAD

**Issue by geoffjukes** [shaka-project/shaka-packager#1085]
Related to #1078 I'm wondering if xHE-AAC support is in the works.

Bento4 appears to process it OK, but the CLI tool I use for DRM packaging is based on Shaka.

Many thanks,

Geoff

**Comment by joeyparrish** [comment]
Nobody is working on it at the moment, but PRs are always welcome.  Thanks!

**Comment by geoffjukes** [comment]
@joeyparrish I'd love to - but I'm so far outside my comfort zone, I'm practically on a different planet.

I'll ask around, see if there's anyone I know who might have the skillset.

**Comment by joeyparrish** [comment]
I apologize we don't have resources dedicated to this at Google!  But we will have to rely more on external contributions for Packager than we used to.  I'm currently working on an overhaul of the build system (in my [20% time](https://en.wikipedia.org/wiki/Side_project_time)) to try to make Packager easier to work in and contribute to, but I don't have the bandwidth to work on features right now.

**Comment by geoffjukes** [comment]
@joeyparrish No need to apologize. I've put in a question to the vendor of the xHE-AAC encoder we use. It's worth asking if they can help at all. Fingers crossed!

**Comment by geoffjukes** [comment]
@joeyparrish

I have in-hand a .patch for Shaka, with a license that grants me "a worldwide,
perpetual, irrevocable, non-exclusive, transferable and assignable copyright
license with the right to sublicense through multiple tiers to use,
copy, distribute, modify and create derivative works of the software in
source code form and/or object code versions of the software".

My reading of that license means I can pull a copy of this repo, apply the patch, and submit a PR - but I'm not a lawyer, and I'm a little nervous about doing it.

**Comment by joeyparrish** [comment]
I am also not a lawyer, and since this project is related to my job, I will avoid saying anything that could be misconstrued as legal advice.  Maybe the author of the patch can give you some clarity if you're unsure.

**Comment by geoffjukes** [comment]
@joeyparrish I've sent a copy to a lawyer and asked the author for clarity. Hope to hear back soon then I can submit a PR 😄

**Comment by geoffjukes** [comment]
PR #1092 Submitted

**Comment by geoffjukes** [comment]
PR #1092 merged. Thanks @joeyparrish !
