### ISSUE TITLE
Question - How to set widevine security level(l3) while packaging dash content.

### ISSUE THREAD

**Issue by Hakai-Shin** [shaka-project/shaka-packager#1087]
I am using the following command to package my mp4 video with widevine
`
packager \
  in=h264_baseline_360p_600.mp4,stream=audio,output=audio.mp4 \
  in=h264_high_1080p_6000.mp4,stream=video,output=h264_1080p.mp4 \
  --enable_widevine_encryption \
  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
  --content_id 7465737420636f6e74656e74206964 \
  --signer widevine_test \
  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 \
  --mpd_output h264.mpd
`
How to set widevine security level at L3 while packaging.

**Comment by joeyparrish** [comment]
The security level isn't a feature of the content AFAICT.  A client has a certain security level (or in some cases, multiple CDMs are available with different security levels).  The license server or license proxy decides which keys to send to the client based on its security level.
