### ISSUE TITLE
Simple FairPlay HLS DRM not working in => v4.0.0

### ISSUE THREAD

**Issue by ahsanghalib** [shaka-project/shaka-packager#1088]
## System info
**Operating System**: <macOS>
**Shaka Packager Version**: <4.2.0>

I have simple Fairplay HLS configuration that works in v3.3.9 but not in any version starting from v4.0.0. 
```
config = {
          drm: {
            servers: {
              "com.apple.fps.1_0": mediaInfo?.drm?.licence_url
            },
            advanced: {
              "com.apple.fps.1_0": {
                serverCertificateUri: mediaInfo?.drm?.cert_url
              }
            }
          }
        };
```

I am getting this error in v4.2.0, I have tried removing 1_0 but didn't work. 

<img width="1276" alt="Screenshot 2022-08-20 at 23 04 57" src="https://user-images.githubusercontent.com/46633676/185760817-449ec3a6-2ce6-4d4f-a6ce-c61e81d0f034.png">

**Comment by joeyparrish** [comment]
It appears that you filed this in the wrong repository.  Please see [shaka-project/shaka-**player**](https://github.com/shaka-project/shaka-player)
