### ISSUE TITLE
mp4_media_parser error -  Failed to process the sample 256 5 

### ISSUE THREAD

**Issue by nirolfa** [shaka-project/shaka-packager#1093]
## System info
**Operating System**: windows
**Shaka Packager Version**: latest version

## Issue and steps to reproduce the problem

**Packager Command**:
\yt-dlp\packager-win-x64 --enable_raw_key_decryption --keys key_id=a086a7
2573ad437b8ecb5afbb573d388:key=0e955e8dffc6a580a0d6056a088e8954 stream=video,in=
demain.ts,output=demain-dec.ts

What is the expected result?
   decrypt file (was working before -> change in provider enconding ? )

What happens instead?
error
[0831/204315:INFO:demuxer.cc(89)] Demuxer::Run() on file 'demain.mp4'.
[0831/204315:INFO:demuxer.cc(155)] Initialize Demuxer for file 'demain.mp4'.
[0831/204325:ERROR:demuxer.cc(356)] Failed to process sample 256 5 (FILE_FAILURE
): Fail to write to file in BufferWriter
[0831/204325:ERROR:mp4_media_parser.cc(889)] Failed to process the sample.
[0831/204325:ERROR:packager_main.cc(554)] Packaging Error: 8 (PARSER_FAILURE): C
annot parse media file demain.mp4

ffprobe of mp4 file:
[h264 @ 000000daa93150c0] top block unavailable for requested intra mode -1
[h264 @ 000000daa93150c0] error while decoding MB 0 0, bytestream 405
[h264 @ 000000daa93150c0] concealing 8160 DC, 8160 AC, 8160 MV errors in I frame

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'demain.mp4':
  Metadata:
    major_brand     : iso6
    minor_version   : 0
    compatible_brands: iso6dash
  Duration: 00:29:11.10, start: 0.040000, bitrate: 5221 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progres
sive), 1920x1080 [SAR 1:1 DAR 16:9], 5192 kb/s, 50 fps, 50 tbr, 600 tbn (default
)
    Metadata:
      handler_name    : USP Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding

**Comment by cosmin** [comment]
missing sample file
