### ISSUE TITLE
AAC 7.1 mpd packaging is falling

### ISSUE THREAD

**Issue by rodolfo-vargas** [shaka-project/shaka-packager#1101]
## System info
**Operating System**: OSX, Linux
**Shaka Packager Version**: v2.6.1 Oct 14, 2021

## Issue and steps to reproduce the problem
use packager to create an MPD with a stream containing audio AAC 7.1 (8chs). The INIT file is NOT right. 5.1 and 2.0 are OK

What is the expected result?
The audio INIT mp4 file is not right.

What happens instead?
The audio INIT mp4 is too small and looks like missing the MP4 info.

It appears that this issue was a BUG, and fixed, but the latest release doesn't include this fix.

**Comment by cosmin** [comment]
Latest release at this point should contain all fixes.
