### ISSUE TITLE
Widevine Policy Option

### ISSUE THREAD

**Issue by Avalonswanderer** [shaka-project/shaka-packager#1105]
During the packaging of content using the system Widevine we can specify the key server of Widevine for testing https://license.uat.widevine.com/cenc/getcontentkey/widevine_test

During such packaging, the option --policy can be used to refer to a stored policy within the key server. If empty the policy will be the "default" one but my question is does anyone know other policy names to try with this key server? For instance to define a license duration, renewal policy, etc...

Thanks in advance

**Comment by cosmin** [comment]
This might be better addressed to Widevine support at https://support.google.com/widevine/troubleshooter/6027072
