### ISSUE TITLE
Is it possible to dynamically inject cue for live video

### ISSUE THREAD

**Issue by cisiwen** [shaka-project/shaka-packager#1125]
Hi team

We using shaka packager for  some vod packaging, but would like to extend the solution to live video.
the requirement is create an api and a player with a button to feed in shaka packager with cue seconds when live video packaging is running.

i don't know if this is possbile at the moment with shaka packager, any suggesion would be helpful.

Thanks

XZ Weng

**Comment by cosmin** [comment]
You would have to build something yourself on top of the shaka packager library.
