### ISSUE TITLE
DASH : how can i test  SCTE 35 markers ( EventStream )  insertion in dash manifest   ?

### ISSUE THREAD

**Issue by dradenvandewind** [shaka-project/shaka-packager#1134]
How configure  shaka-streamer  to  obtain   eventstream in dash manifest ?

this issue seems say "support EventStream in DASH manifests"
https://github.com/shaka-project/shaka-player/issues/462

thanks a lot in avance.
regards

**Comment by joeyparrish** [comment]
I don't understand your issue.  You have posted in shaka-packager, but asked about shaka-streamer, then linked to a shaka-player issue.

Can you explain what you are trying to do, and with what tools?

**Comment by dradenvandewind** [comment]
I have found this tutorial https://shaka-project.github.io/shaka-packager/html/tutorials/ads.html  for try this features. 
I want to insert dynamically spliced ​​events to meet my need? is this possible if I do it at the level of the ts muxer? will shaka packager detect them and add an "eventstream" tag in dash manifest? thanks a lot in avance for your advice

**Comment by joeyparrish** [comment]
I've only recently taken over the project, so I don't have prior knowledge of this feature.  But there is nothing in the source code that mentions `EventStream`.

Quoting that tutorial, though:

> Shaka Packager does not do Ad Insertion directly, but it can precondition content for [Dynamic Ad Insertion](http://bit.ly/2KK10DD) with Google Ad Manager.  Both DASH and HLS are supported.

Are you trying to use Google Ad Manager?  Shaka Packager's ad support is designed to integrate with Google Ad Manager.  I don't have much experience with Ad Manager, so I don't know if Ad Manager might insert SCTE35 markers in DASH.

**Comment by dradenvandewind** [comment]
![eventstream](https://user-images.githubusercontent.com/8048792/200251512-eb3b9ae9-81c0-42d5-a84e-9a37d7ec4f8c.png)
hello joey , see in attachment  this source code mentions EventStream

**Comment by joeyparrish** [comment]
It is mentioned in an MPD schema validator (declares that it exists in the MPD format).

It appears again in packager/base/, which is a third-party library from Chromium.  In that context, it refers to something related to the filesystem.

**Comment by vish91** [comment]
> I have found this tutorial https://shaka-project.github.io/shaka-packager/html/tutorials/ads.html for try this features. I want to insert dynamically spliced ​​events to meet my need? is this possible if I do it at the level of the ts muxer? will shaka packager detect them and add an "eventstream" tag in dash manifest? thanks a lot in avance for your advice

@dradenvandewind  per docs
```
--ad_cues <start_time[;start_time]…>
This flag preconditions content for [Dynamic Ad Insertion](http://bit.ly/2KK10DD) with Google Ad Manager. For DASH, multiple periods will be generated with period boundaries at the next key frame to the designated start times; For HLS, segments will be terminated at the next key frame to the designated start times and ‘#EXT-X-PLACEMENT-OPPORTUNITY’ tag will be inserted after the segment in media playlist
```
With this flag packager can signal ad cues. It places proper HLS tag in manifest or for DASH it allows to generate multi period dash. For this when encoding you will need key frames at those boundaries so segments can be split at those. 
Could you explain more on how you are encoding and if this is what you are expecting to generate with packaging ad cue placement ?

**Comment by dradenvandewind** [comment]
@vish91 i have test this ad_cues  flag   for start shaka packager  in live mode.  I don't see new section in my mpd file, this feature does not seem to work  This ad_cues flags works only in vod ? i dont try it

**Comment by cosmin** [comment]
@dradenvandewind do you have an example command line that is not working?
