### ISSUE TITLE
Can I be given a service certificate + documentation access as a free licensee or am I required to pay an integrator?

### ISSUE THREAD

**Issue by uwuforever** [shaka-project/shaka-packager#1137]
I have all the software set up already with PlayReady, afaik being the same protocols that they are interchangeable, and am more than capable of adding a few more lines of config. I'm not looking to integrate for third parties.

On the site, this implies that that should be free if I sign a license agreement. 

> A license agreement is required for the use of Widevine products or services. Widevine does not assess any fee for use of its products and services.

Yet I never get an answer, and now I'm wondering, where they say they don't directly support end users, I guess to them am I also and user? If I'm required to go that route, anyone have a recommendation for a cheap integrator I could pay one time to set me up with access to my own certificate + documentation? Once I have it I have it forever even if I bring it to a future job?

**Comment by uwuforever** [comment]
I'm really tempted to just use the ancient certificate I found on github now, although I have no clue on whether or not  it's still valid or if the actual owner still uses it... but I'd also like to just have proper documentation and not need to guess on something like that, especially if it should be free anyways...

**Comment by joeyparrish** [comment]
I'm a bit confused by your post, but it sounds like you're asking about how to package content for Widevine.

End-users are the people who are watching Widevine-encrypted videos.  If you're the person doing the encryption and streaming, you're not an end-user.

To use Widevine in a streaming service, you'll need to contact Widevine, sign a license agreement, do some amount of training on the product, then get credentials to sign license requests/responses.  You'll have to run your own license server or proxy.

At least, that was roughly the process as I knew it when I was a Widevine engineer.  (I'm not any more.)

Does this help?

**Comment by uwuforever** [comment]
I'm trying to set up my own license server. I have them for Playready and Fairplay already so I assume setting up will be similar right?

My understanding is the CWIP program where they train an integrator is something with an annual fee and requires 2 committed employees. I assumed there'd have been a way to just get the docuentation + credentials to figure out yourself like the other 2 services do, though but they don't seem to ever answer any inquiries like that.

**Comment by joeyparrish** [comment]
Yeah, the CWIP program is what I'm familiar with.  I used to teach the Shaka Player section there.

I don't believe you can run a license server without signing a license agreement with Widevine.  At least, that was the way it was when I was there.  I don't know if that has changed since I left.  I also don't know if you can sign the agreement without doing CWIP.

I hear you that this seems more difficult than PlayReady and Fairplay.  I'm sorry I don't personally know any more than this, and that my information may be out of date.

**Comment by joeyparrish** [comment]
I heard back from a contact at Widevine.  They said:

> CWIP is not a pre-requisite.  The sales team have calls with organizations interested in using Widevine.  If they want additional help with onboarding, they can sign up for CWIP, get access to additional documentation (and training in non-COVID times).  But those who opt to do everything on their own can still get software and credentials.  They can reach out to us here: https://support.google.com/widevine/troubleshooter/6027072, option 2

Does this help?
