### ISSUE TITLE
DASH : add_cue parameters  no works with packager version d5ca6e84e6-release

### ISSUE THREAD

**Issue by dradenvandewind** [shaka-project/shaka-packager#1138]
hello,
This feature no works.

I encoded my input as follows:

 ffmpeg -i input_file.mkv -codec:a aac \
  -vf "scale=-2:480" \
  -c:v libx264 -profile:v main -level:v 3.1 \
  -x264-params scenecut=0:open_gop=0:min-keyint=240:keyint=240 \
  -minrate 1000k -maxrate 1000k -bufsize 1000k -b:v 1000k \
  -y /media/eleblond/T721/poc_scte35/video/cyim_h264_main_480p_1000.mp4

/usr/bin/packager 'in=h264_main_480p_1000.mp4,stream=video,init_segment=h264_480p/init.mp4,segment_template=h264_480p/$Time$.m4s' --ad_cues 240,480 --generate_static_live_mpd --mpd_output /home/adcue.txt

[adcue.txt](https://github.com/shaka-project/shaka-packager/files/9979768/adcue.txt)

**Comment by dradenvandewind** [comment]
i don't see extra tags in manifest ( adcue.txt )

**Comment by dradenvandewind** [comment]
for HLS OUTPUT :
/usr/bin/packager 'in=intra-refresh_cyim_h264_main_480p_1000.mp4,stream=video,init_segment=h264_480p/init.mp4,segment_template=h264_480p/$Time$.m4s' --ad_cues 60,120,240,480 --hls_master_playlist_output /home/master.hls

I see the tags to insert advertising EXT-X-PLACEMENT-OPPORTUNITY

**Comment by dradenvandewind** [comment]
For dash output : do you know a tag or commit where this feature was functional?

**Comment by cosmin** [comment]
Just tested this with latest 3.0.x release and --ad_cues works as expected, for DASH it generates an MPD with multiple periods, providing an opportunity for ad insertion between the periods.
