### ISSUE TITLE
"Marrying" audio tracks with video tracks, HLS output

### ISSUE THREAD

**Issue by Lars** [shaka-project/shaka-packager#1141]
Hello all.

I'm migrating from a setup using ffmpeg encoding and hls packaging (plus manual master manifest creation) to ffmpeg encoding and Shaka packaging.

My trouble is, appart from a video ladder, I produce an Audio ladder. Same audio source (language) gets encoded at 256, 128, 64 and 32kbps aac depending on the video resolution since the target of this material is a country with a very very bad connection standard so lower resolutions and audios are intended to render the material viewable (if at a low quality) for people with very very bad connections.

My problem is, in ffmpeg packaging I just used to produce .ts files with video AND audio, so higher video resolutions carried higher audio ones.

With shaka it seems I can't produce hybrid .ts in a single playlist... so I'm wondering if there's a way I can define several audio streams, for different compression levels, not language, and associate those to their respective video tracks (256Kb aac for 1080p video, etc)....

Failing that, should using same language audios in the main manifest be workable so that a player (I use video.js not Shaka player) will step down between the audios the same as with video resolutions rather than showing them as options? I guess that one would take recoding the player to include this functionality....

**Comment by cosmin** [comment]
Merging to #770
