### ISSUE TITLE
Add missing values for DASH role scheme

### ISSUE THREAD

**Issue by dudewheresmycode** [shaka-project/shaka-packager#1149]
## System info
**Operating System**: Debian GNU/Linux 11 (bullseye)
**Shaka Packager Version**: `shaka-packager version v2.6.1-634af65-release`

## Issue and steps to reproduce the problem

I'm running into an issue setting the `roles` stream descriptor option for content containing descriptive audio tracks. The DASH spec specifically defines these as:

> `description` - Textual or audio media component containing a textual description (intended for
audio synthesis) or an audio description describing a visual component.

From the `shaka-packager` docs, it appears it only supports a subset of the values outlined in the DASH specification:

> Optional semicolon separated list of values for DASH Role element. The value should be one of: `caption`, `subtitle`, `main`, `alternate`, `supplementary`, `commentary` and `dub`. See DASH (ISO/IEC 23009-1) specification for details.

However, checking the DASH (ISO/IEC 23009-1) specification, section 5.8.5.5 DASH role scheme (Table 29), defines many more values for the roles:
- `caption`
- `subtitle`
- `main`
- `alternate`
- `supplementary`
- `commentary`
- `dub`
- `description`
- `sign`
- `metadata`
- `enhanced-audio-intelligibility`
- `emergency`

**Packager Command**:
```bash
shaka-packager \
in=./input.mp4,stream=video,init_segment=./video/video_init.mp4,segment_template=./video/video_$Number$.m4s \
in=./input.mp4,stream=audio,language=en,roles=main,init_segment=./audio/audio_main_init.mp4,segment_template=./audio/audio_main_$Number$.m4s \
in=./descriptive-audio.mp4,stream=audio,language=en,roles=description,init_segment=./audio/audio_desc_init.mp4,segment_template=./audio/audio_desc_$Number$.m4s \
--fragment_duration 6 --segment_duration 6 --generate_static_live_mpd --mpd_output ./manifest.mpd
```

Extra steps to reproduce the problem?
(1) include `roles=description` in DASH stream descriptor options

What is the expected result?
Generates a DASH manifest with a `description` role

What happens instead?
Shaka throws an error:
```
[1127/214613:ERROR:period.cc(208)] Unrecognized role 'description'
```

**Comment by dudewheresmycode** [comment]
I see that support for `description` specifically was added in [this commit](https://github.com/shaka-project/shaka-packager/commit/dc0395291a090b342beaab2e89c627dc33ee89b0), so I'm guessing this just hasn't made it into a release yet?

**Comment by dudewheresmycode** [comment]
Just wanted to check in on this. Any chance we can get a new release tagged that contains this fix?

**Comment by dudewheresmycode** [comment]
Just wanted to bump this again. Any chance we could get a new release tagged? The fix for this was merged nearly a year ago now.

**Comment by cosmin** [comment]
version 3.0.x should contain anything that was previously merged, I'll look at adding any missing values
