### ISSUE TITLE
Build from source fails: ninja.build nor found

### ISSUE THREAD

**Issue by A-nglea** [shaka-project/shaka-packager#1158]
Fedora 37
ninja: error: loading 'build.ninja': No such file or directory

followed https://github.com/shaka-project/shaka-packager/blob/main/docs/source/build_instructions.md

**Comment by joeyparrish** [comment]
This will be obsoleted by #1047, which we are in the middle of.  The entire build system is being replaced with CMake.

**Comment by ksa-real** [comment]
Is there any way to build shaka-packager from source nowadays? Instructions for macos don't work for me. `./gyp_packager.py` doesn't work (No module named 'gyp_helper'), gclient runhooks seems to be doing nothing. I tried checking out `main` branch in --no-checkout src directory. Then `gclient runhooks -v` tries to build the project but fails with `sed: can't read src/packager/build/common.gypi: No such file or directory`.

**Comment by cosmin** [comment]
You can build from the `cmake` branch for now. This should build a fully functional packager application although we still need to put some finishing touches on it prior to merging into main.
