### ISSUE TITLE
Adding SUPPLEMENTAL-CODECS tag according to new HLS specs

### ISSUE THREAD

**Issue by XingzhaoYun** [shaka-project/shaka-packager#1164]
HLS has released latest HLS specs and adding optional SUPPLEMENTAL-CODECS tag (https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis), is there any plan for supporting this tag? thanks!

**Comment by joeyparrish** [comment]
I was unaware of that tag, but let's add it as a feature request.  I could see this being useful not only for Dolby Vision as mentioned in the spec, but perhaps also for LCEVC.

**Comment by joeyparrish** [comment]
PRs are always welcome!

**Comment by sr1990** [comment]
Hi @XingzhaoYun , for DASH, it looks like @scte214:supplementalCodecs and @scte214:supplementalProfiles can be used to indicate supplemental codecs as per https://professionalsupport.dolby.com/s/article/How-to-signal-Dolby-Vision-in-MPEG-DASH?language=en_US

One possible solution:  
1) Add an option in MuxerOptions to enable specifying supplemental codec. Example: --enable_supplemental_codecs

2) Add supplemental codec as data member in [StreamInfo](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/media/base/stream_info.h#L67)
In [MultiCodecMuxerListener::OnMediaStart](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/media/event/multi_codec_muxer_listener.cc#L16), set the supplemental_codec in StreamInfo if --enable_supplemental_codecs flag is enabled.

3) In MediaInfo’s [VideoInfo](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/mpd/base/media_info.proto#L23), add supplemental codec.

4) HLS
In [HlsNotifyMuxerListener::OnMediaStart](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/media/event/hls_notify_muxer_listener.cc#L89), set the supplemental codec value while creating MediaInfo.
Update [MediaPlaylist](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/hls/base/media_playlist.h#L260) to have supplemental_codec and initialize supplemental_codec if present in media info in https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/hls/base/media_playlist.cc#L373

While writing the master playlist [MasterPlaylist::WriteMasterPlaylist](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/hls/base/master_playlist.cc#L498), in [BuildStreamInfTag](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/hls/base/master_playlist.cc#L194),  add SUPPLEMENTAL-CODECS to the playlist if available.

5) For DASH
Add supplemental codec as data member in [Adaptation Set](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/mpd/base/adaptation_set.h#L33) and [Representation](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/mpd/base/representation.h#L50).
In [AdaptationSet::AddRepresentation](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/mpd/base/adaptation_set.cc#L181), create a new representation with supplemental codecs if present.
In [Representation::GetXml](https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/mpd/base/representation.cc#L252), add @scte214:supplementalCodecs and @scte214:supplementalProfiles if supplemental codecs are present.

**Comment by cosmin** [comment]
This is now implemented in 3.2 when running with `--use_dovi_supplemental_codecs` as changing the default behavior woudl be a breaking change.

**Comment by joeyparrish** [comment]
@cosmin, I'm curious, what part of it would be a breaking change?

**Comment by cosmin** [comment]
Currently when given an input with DolbyVision packager outputs a manifest/playlist with 2 entries, one with DolbyVision as the codec and one with the base codec. Switching to supplemental codecs would replace that with a single entry using supplemental codecs tagging, which may or may not be supported in all the players yet.
