### ISSUE TITLE
How to build on M1 mac?

### ISSUE THREAD

**Issue by thesyntaxinator** [shaka-project/shaka-packager#1167]
When I try to build on an M1 mac with gclient within the specified branch of depot-tools I get `Platform mac-arm64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.`

**Comment by joeyparrish** [comment]
I believe this will be fixed in the cmake port.  The build system in `main` is antiquated and broken in many ways, but we are rewriting all of that in the `cmake` branch (currently incomplete).

**Comment by cosmin** [comment]
The cmake branch is now feature complete although it still needs some finishing touches prior to merging into main. To build you can run 

```
git submodule update --init --recursive
cmake build -G Ninja
cmake --build build --parallel
```
