### ISSUE TITLE
E2E tutorial on DRMs

### ISSUE THREAD

**Issue by misiek08** [shaka-project/shaka-packager#1171]
Is there any end-to-end tutorial from an input file/stream to working player in HTML code? I'm trying to setup whole pipeline, but still getting issues with the last step - just playing the DASH or HLS in shaka-player at the end.

## System info
**Operating System**: latest Ubuntu, doesn't matter
**Shaka Packager Version**: 2.6.1

## Issue and steps to reproduce the problem

Setting up multi-DRM packaging and player.

## What is the expected result?

Working setup :)

## What happens instead?

Player is not playing media.

**Comment by cosmin** [comment]
if you are having problems integrating with the Widevine license server please reach out to Widevine https://support.google.com/widevine/troubleshooter/6027072
