### ISSUE TITLE
Packaging Error: 5 on ec2 t2.medium

### ISSUE THREAD

**Issue by ashraf-minhaj** [shaka-project/shaka-packager#1185]
## System info
**Operating System**:  Ubuntu Jammy 22.04 (AWS ec2, t2.medium)
**Shaka Packager Version**: 2.6.1

## Issue and steps to reproduce the problem
Trying to package a large file (size more than 700mb)

What happens?
Packaging Error: 5 (FILE_FAILURE): Cannot close the temp file /tmp/.org.chromium.Chromium.IlCd7u, possibly file permission issue or running out of disk space

**Comment by vish91** [comment]
@ashraf-minhaj  this is likely seen when your instance in this case an ec2 -t2.medium doesn't have enough space to generate store temp files or complete the packaging. 
Check or try running the same locally and see if you still have same problem.  Also depends on what packager command you are running and what are all the inputs / outputs from command.
