### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' encountered when running `pssh-box.py` tool, patch included.

### ISSUE THREAD

**Issue by Brainiarc7** [shaka-project/shaka-packager#1191]
## System info
**Operating System**:Ubuntu 22.04LTS
**Shaka Packager Version**: git tip master

## Issue and steps to reproduce the problem:

Any invocation of `pssh-box.py` tool fails with the error:
```sh
TypeError: a bytes-like object is required, not 'str'
```
On line 170. 

I've pushed a patch #1187 to address this, please review.

**Comment by cosmin** [comment]
Closed by #1187
