### ISSUE TITLE
arm64 binaries for v2.4.3

### ISSUE THREAD

**Issue by rottolia-fubotv** [shaka-project/shaka-packager#1193]
Hello, would it possible to get arm64 compatible binaries for v2.4.3 of packager/mpd_generator? from the releases, I understand that arm64 binaries were only included in v2.6.0 releases at the earliest. Attempted to follow build instructions but ran in to numerous build issues, many of which are also documented elsewhere in issues. As I understand there is a build migration project in process that attempts to resolve some of these. Thanks.

**Comment by joeyparrish** [comment]
You can definitely build those yourself from source, but there are no official arm64 builds from that time.
