### ISSUE TITLE
Build errors while cross-compiling v2.4.3 for arm64

### ISSUE THREAD

**Issue by rottolia-fubotv** [shaka-project/shaka-packager#1194]
## System info
**Operating System**: Ubuntu 14.04.6 
**Shaka Packager Version**: v2.4.3

Running into errors while trying to build v2.4.3 of shaka according to docs.

## Issue and steps to reproduce the problem

Follow build instructions as per: https://github.com/shaka-project/shaka-packager/blob/main/docs/source/build_instructions.md#cross-compiling-for-arm-on-ubuntu-host

Extra steps to reproduce the problem?
(1) clone v2.4.3 with `gclient sync -r v2.4.3 --no-history`
(2) cd `src` and `GYP_CROSSCOMPILE=1 GYP_DEFINES="target_arch=arm64" gclient runhooks`
(3) run `ninja -C out/Release`

What is the expected result?

Shaka packager and mpd_generator binaries built for amd64 architecture

What happens instead?

build fails with error:
```
[31/31] LINK mpd_generator
FAILED: mpd_generator
../../packager/third_party/llvm-build/Release+Asserts/bin/clang++  -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -Wl,--disable-new-dtags -target aarch64-linux-gnu --sysroot=/home/ubuntu/shaka_packager_arm/src/packager/build/linux/debian_jessie_arm64-sysroot -L/home/ubuntu/shaka_packager_arm/src/packager/build/linux/debian_jessie_arm64-sysroot/lib/aarch64-linux-gnu -Wl,-rpath-link=/home/ubuntu/shaka_packager_arm/src/packager/build/linux/debian_jessie_arm64-sysroot/lib/aarch64-linux-gnu -L/home/ubuntu/shaka_packager_arm/src/packager/build/linux/debian_jessie_arm64-sysroot/usr/lib/aarch64-linux-gnu -Wl,-rpath-link=/home/ubuntu/shaka_packager_arm/src/packager/build/linux/debian_jessie_arm64-sysroot/usr/lib/aarch64-linux-gnu -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -Wl,--no-as-needed -lpthread -Wl,--as-needed -o mpd_generator -Wl,--start-group obj/app/mpd_generator.mpd_generator.o obj/app/mpd_generator.vlog_flags.o obj/base/libbase.a obj/mpd/libmpd_util.a obj/third_party/gflags/libgflags.a obj/tools/liblicense_notice.a obj/base/libbase_static.a obj/third_party/modp_b64/libmodp_b64.a obj/base/third_party/dynamic_annotations/libdynamic_annotations.a obj/base/libsymbolize.a obj/base/libxdg_mime.a obj/base/third_party/libevent/libevent.a obj/base/allocator/libunified_allocator_shim.a obj/file/libfile.a obj/mpd/libmpd_builder.a obj/media/base/libmedia_base.a obj/media/base/libwidevine_common_encryption_proto.a obj/third_party/protobuf/libprotobuf_full_do_not_use.a obj/media/base/libwidevine_pssh_data_proto.a obj/libstatus.a obj/third_party/boringssl/libboringssl.a obj/third_party/boringssl/libboringssl_asm.a obj/third_party/curl/libcurl.a obj/third_party/libxml/libxml2.a obj/third_party/icu/libicuuc.a obj/third_party/zlib/libchrome_zlib.a obj/third_party/zlib/libzlib_x86_simd.a obj/version/libversion.a obj/mpd/libmanifest_base.a obj/mpd/libmedia_info_proto.a obj/mpd/libmpd_mocks.a obj/testing/libgmock.a obj/testing/libgtest.a -Wl,--end-group  -lrt -ldl -lm
/usr/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 i386linux elf_l1om elf_k1om i386pep i386pe

```
<Please provide any additional information below.>

Verified that the arm cross toolchain libs referenced in `install-build-deps.sh` are installed via apt-get:

- libc6-dev-armhf-cross
- linux-libc-dev-armhf-cross
- g++-arm-linux-gnueabihf
- g++-4.8-multilib-arm-linux-gnueabihf
- gcc-4.8-multilib-arm-linux-gnueabihf

Am I missing a step here? any help much appreciated.

**Comment by joeyparrish** [comment]
It's using a clang toolchain from packager/third_party/llvm-build instead of what you have installed.

Please try this in place of the runhooks command:

```sh
GYP_CROSSCOMPILE=1 GYP_DEFINES="target_arch=arm clang=0" gclient runhooks
```

That clang=0 flag was removed by v2.6 along with the internal toolchains, but it might do the trick for v2.4.

**Comment by rottolia-fubotv** [comment]
@joeyparrish That did the trick.  I ran into a compilation issue similar to the one described here: https://github.com/shaka-project/shaka-packager/issues/694 but the details there helped me resolved it.  Thanks for your help!

**Comment by joeyparrish** [comment]
Happy to help.  I hope that the forthcoming build system improvements in v2.7 (moving to CMake) help simplify your next build!
