### ISSUE TITLE
AV1 encoding missing color metadata

### ISSUE THREAD

**Issue by cosmin** [shaka-project/shaka-packager#1202]
Given any AV1 encoding in MP4 format, the output MPD is missing color information from the dash codec string, and the output mp4 is missing the color information in `av1C` (the entire `colr` box is missing).

> For example, codecs="av01.0.04M.10.0.112.09.16.09.0" represents AV1 Main Profile, level 3.0, Main tier, 10-bit content, non-monochrome, with 4:2:0 chroma subsampling co-located with (0, 0) luma sample, ITU-R BT.2100 color primaries, ITU-R BT.2100 PQ transfer characteristics, ITU-R BT.2100 YCbCr color matrix, and studio swing representation.

> The parameters sample entry 4CC, profile, level, tier, and bitDepth are all mandatory fields. If any of these fields are empty, or not within their allowed range, the processing device SHOULD treat it as an error. All the other fields (including their leading '.') are optional, mutually inclusive (all or none) fields. If not specified then the values listed in the table below are assumed.

The color fields are optional, so the current output is a valid MPD. Previously packager used to output only partial color information which was incorrect, as the optional fields are mutually inclusive (all or none). Related issue was #453 and this was fixed in 53aa775ea488c by removing all the optional fields.

Instead we should properly parse the color information from `av1C/colr`, populate the dash codec string, and then also pass down the `colr` atom in `av1C`.

**Comment by joeyparrish** [comment]
Thank you for the detailed write-up!  PRs are very welcome.

**Comment by joeyparrish** [comment]
Closed by #1261
