### ISSUE TITLE
vp9 codec processing error

### ISSUE THREAD

**Issue by sgbai78** [shaka-project/shaka-packager#1207]
## System info
**Operating System**: windows 11
**Shaka Packager Version**: v2.6.1-634af65-release

## Issue and steps to reproduce the problem

**Packager Command**:
packager 'in=nosound.mkv,stream=video,init_segment=nosound_init.webm,segment_template=video/nosound/video_1080p_2M_vp9_$Number$.webm' --segment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output video/nosound/hls.m3u8

Extra steps to reproduce the problem?
(1) I did the encoding with the command below.
     ffmpeg -i input.mp4 -c:v libvpx-vp9 -an nosound.mkv

(2) Then I ran the packager like this
packager 'in=nosound.mkv,stream=video,init_segment=nosound_init.webm,segment_template=video/nosound/video_1080p_2M_vp9_$Number$.webm' --segment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output video/nosound/hls.m3u8

What is the expected result?
Video should play normally.

What happens instead?
If you check the result file using ffprobe, an 'Invalid data found when processing input' error occurs as shown below.

[matroska,webm @ 000001550dc4b4c0] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 000001550dc4b4c0] EBML header parsing failed
video_1080p_2M_vp9_10.webm: Invalid data found when processing input

<Please attach the input files or email to shaka-packager-issues@google.com.>

https://github.com/shaka-project/shaka-packager/assets/75677950/8380fb21-f811-40c6-90d0-25e3254324a2

<Please provide any additional information below.>
I am planning to stream using vp9.
This problem only seems to occur when using the vp9 codec.

**Comment by cosmin** [comment]
The attached file fails to download, produces 0 bytes. I tested just now with latest ffmpeg encoding a video with VP9 in MKV and packager has no problems reading it. The 

```
[matroska,webm @ 000001550dc4b4c0] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 000001550dc4b4c0] EBML header parsing failed
```

suggests the input file is corrupted because it failed to parse proper EBML. I suggest checking the transcoding command to make sure it runs successfully and produces well formed output (try decoding it again with ffmpeg to confirm).
