### ISSUE TITLE
When using http for output, the output url cannot have $ character

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-packager#1225]
## System info
**Operating System**: All OS
**Shaka Packager Version**: 2.6.1

## Issue and steps to reproduce the problem
packager in=test.mp4,stream=video,out=http://localhost:8080/$test/video.mp4
**Packager Command**:

Extra steps to reproduce the problem?
(1) create a small web server (I tested with a nodejs sample that can accept put and write to a file)
(2) run the packager command to output to http.

What is the expected result?
The command should succeed
What happens instead?
[0707/153327:ERROR:packager_main.cc(549)] Failed to initialize packager: 3 (INVALID_ARGUMENT): In segment templates $Number$ or $Time$ should exist.
<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

When writing to a single file the validator still expects $Time or $Number and escaping of $$ doesn't work.

**Comment by cosmin** [comment]
I think the presence of $ is triggering the segment template validation. This comment in muxer.cc seems relevant

https://github.com/shaka-project/shaka-packager/blob/main/packager/media/base/muxer.cc#L23

> // "$" is only allowed if the output file name is a template

**Comment by xavierlaffargue** [comment]
Indeed, @duggaraju you can use $$ to escape $ : (https://shaka-project.github.io/shaka-packager/html/tutorials/hls.html#segment-template-formatting) 

`packager in=test.mp4,stream=video,out=http://localhost:8080/$$test/video.mp4`
