### ISSUE TITLE
How would I use the Shaka packager to generate a DASH manifest from already-existing .webm audio and video files?

### ISSUE THREAD

**Issue by kshetline** [shaka-project/shaka-packager#1300]
## System info
Windows 11
Shaka packager v2.6.1-634af65-release

## Issue and steps to reproduce the problem

I have already-generated .webm audio and video files (1 audio, 3 video resolutions for each video I want to stream). They don't need to be (or, as far as I know, shouldn't need to be) encoded again. All I want the packager to do is to generate a DASH .mpd manifest for these existing files.

I've been using ffmpeg for this, but it's sporadically rejecting my video input files with the error "Error parsing Cues... Operation not permitted". The video files have been generated by HandbrakeCLI exactly the same way for the video files that do work, and the video files that don't, so the reason for this failure is a mystery.

I'd like to give Shaka packager a try to see if it works better for me, but the stream parameters are all about both input and output. I can't figure out a syntax that will simply use the output I've already generated at various resolutions and do nothing more than create a manifest file for me.

What would the Shaka packager equivalent (if it exists) of this be?

`ffmpeg -f webm_dash_manifest -i '.\My Video.v480.webm' -f webm_dash_manifest -i '.\My Video.v720.webm' -f webm_dash_manifest -i '.\My Video.v1080.webm' -f webm_dash_manifest -i '.\My Video.audio.webm' -c copy -map 0 -map 1 -map 2 -map 3 -f webm_dash_manifest -adaptation_sets "id=0,streams=0,1,2 id=1,streams=3" '.\My Video.mpd'`

I can't even tell from the documentation how I'd using quoting or escaping to deal with spaces in file names either. (Please, the last comment is an aside, not the most important problem!)

**Comment by cosmin** [comment]
Shaka doesn't do any encoding, but it cannot (as far as I know) take the input and leave it exactly as is and just generate the MPD. It packages the input into appropriate format, which may end up being identical to your input depending on how the input was created, but it always does the packaging so needs both an input and an output specified.
