### ISSUE TITLE
(macOS) mbedtls dep failure

### ISSUE THREAD

**Issue by kevleyski** [shaka-project/shaka-packager#1314]
## System info
macOS Sonoma 14.1.1 (23B81)
(main)  https://github.com/shaka-project/shaka-packager/commit/3e71302ba46e5164db91495c5da5ba07fc88cfca

## Issue and steps to reproduce the problem
Third party dep failure

[159/821] Building C object packager/third_party/mbedtls/source/library/CMakeFiles/mbedcrypto.dir/psa_crypto_client.c.o
FAILED: packager/third_party/mbedtls/source/library/CMakeFiles/mbedcrypto.dir/psa_crypto_client.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I/Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/.. -I/Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/../include -I/Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/third_party/mbedtls/source/include -I/Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/third_party/mbedtls/source/library -Wall -Wextra -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wvla -Wformat=2 -Wno-format-nonliteral -Werror -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O0 -g3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fcolor-diagnostics -Wall -Wextra -Werror -Wno-unknown-warning-option -Wno-unused-but-set-variable -MD -MT packager/third_party/mbedtls/source/library/CMakeFiles/mbedcrypto.dir/psa_crypto_client.c.o -MF packager/third_party/mbedtls/source/library/CMakeFiles/mbedcrypto.dir/psa_crypto_client.c.o.d -o packager/third_party/mbedtls/source/library/CMakeFiles/mbedcrypto.dir/psa_crypto_client.c.o -c /Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/third_party/mbedtls/source/library/psa_crypto_client.c
In file included from /Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/third_party/mbedtls/source/library/psa_crypto_client.c:22:
/Users/kevin.staunton-lambert/workspace/github_kevleyski/shaka-packager/packager/third_party/mbedtls/source/include/psa/crypto.h:91:23: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]

**Comment by kevleyski** [comment]
(probably useful)
https://github.com/Mbed-TLS/mbedtls/issues/6960

**Comment by kevleyski** [comment]
(hmm Ubuntu build didn't seem to build either, might be a clib/g++ version dep , bit low on time today - will look at it later, maybe I should stick with Docker :-)

**Comment by simonbcn** [comment]
Same problem on MacOS Sonoma 14.2.1 and Clang 15.

**Comment by joeyparrish** [comment]
@kevleyski, @simonbcn, can you please test again with the latest from `main`?  There have been many changes since the commit you referenced from December 1st, including upgrades to zlib, protobuf, and absl, and a change to stop treating warnings as errors in third_party dependencies.  My hope is that one of these many changes has resolved the issue.  If not, we can try an update to mbedtls, since the linked issue is closed there.

**Comment by cosmin** [comment]
I could previously reproduce this with clang 15 on my Mac as well (so I had to pin clang to 14 to build). It now works properly with Clang 15. The change to not treat warnings as errors in 3rd party libs fixed this issue.
