### ISSUE TITLE
Unable to package large media files with DRM (PlayReady, Widevine, Fairplay)

### ISSUE THREAD

**Issue by demz20** [shaka-project/shaka-packager#1315]
## System info
**Operating System**: Windows 11 Enterprise
**Shaka Packager Version**: v2.6.1-634af65-release

## Issue and steps to reproduce the problem

**Packager Command**:

**DRM Playready/Widevine

packager 
in=input.mp4,stream=audio,output=audio.mp4,drm_label=AUDIO 
in=input.mp4,stream=video,output=video.mp4,drm_label=SD 
--enable_raw_key_encryption 
--keys label=AUDIO:key_id=KID:key=KEY,label=SD:key_id=KID:key=KEY 
--protection_systems Widevine,PlayReady 
--mpd_output output.mpd

**DRM Fairplay
packager 
in=input.mp4,stream=video,output=video.mp4,drm_label=HD 
in=input.mp4,stream=audio,output=audio.mp4,drm_label=AUDIO 
--protection_scheme cbcs 
--enable_raw_key_encryption 
--keys label=AUDIO:key_id=KID:key=KEY:iv=IV,label=HD:key_id=KID:key=KEY:iv=IV
--protection_systems FairPlay 
--hls_master_playlist_output h264_master.m3u8 
--hls_key_uri hls_key_provider_url

I just encountered an issue where, when packaging large media, the packager will throw an exception. I can package MP4 media with file sizes less than 400 MB using the above configuration. But when packaging media with file sizes above 400 MB, the packager will not succeed. I could not attach the media files due to confidentiality. Any help would be greatly appreciated!

What is the expected result?
It should package the media.

What happens instead?
It throws this error 
![image](https://github.com/shaka-project/shaka-packager/assets/39882384/c886419c-fca0-40be-8f8e-068016789924)

**Comment by demz20** [comment]
> [https://download.blender.org/demo/movies](https://download.blender.org/demo/movies/BBB/bbb_sunflower_2160p_60fps_normal.mp4.zip)

hi @xavierlaffargue , I have that media, unfortunately, I encountered an error. I do not know if it needs to be fragmented first or let the shaka packager do the fragmentation. Here's the error message: 
![image](https://github.com/shaka-project/shaka-packager/assets/39882384/c1d97994-3a80-4e37-a1e0-e83ffd055499)

**Comment by cosmin** [comment]
Is this problem specifically with DRM, or are you seeing the same problem with large inputs without DRM being applied?
