### ISSUE TITLE
Overall project status

### ISSUE THREAD

**Issue by barak3d** [shaka-project/shaka-packager#1328]
## System info
**Operating System**: Linux
**Shaka Packager Version**: v2.6.1

## Issue description
I would like to add labels to DASH audio tracks, but I could not find any option to do so in the [documentation](https://shaka-project.github.io/shaka-packager/html/).
I noticed that there is an open pull request for this feature https://github.com/shaka-project/shaka-packager/pull/1175.
The last correspondence in the PR was on Jul 2023, but it has not been merged yet.
Is this feature still under development or review? If so, when can we expect it to be available?

## Project status
I also observed that the last commit to the repository was two months ago, but the latest release was v2.6.1 in October 2021. Is this project still active and maintained? Are there any plans for future updates or releases?

**Comment by joeyparrish** [comment]
The project is in a transition, but we hope to release v3.0.0 soon.  We have completely replaced the build system and all dependencies.  You can see the WIP in the `main` branch now.  The v3.0.0 release won't be much different from `main` today.  I'm just reviewing feature PRs to see what else we can land in that release.

**Comment by joeyparrish** [comment]
You can follow along on https://github.com/shaka-project/shaka-packager/pull/1312 as we burn down a small list of issues before deploying v3.0.0.  When that PR is merged, an automated release will occur.

**Comment by barak3d** [comment]
@joeyparrish  Thanks for the updates and for pushing forward a new release with the much anticipated changes!
