### ISSUE TITLE
Warning: "Insufficient bits in bitstream for given AVC profile"

### ISSUE THREAD

**Issue by agiudiceandrea** [shaka-project/shaka-packager#1332]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: 2.6.1

## Issue and steps to reproduce the problem

**Packager Command**:

`shaka-packager in=enc_video.mp4,stream=video,output=/dec_video.mp4 --enable_raw_key_decryption --keys {decryption_key}`

What is the expected result?

No warning

What happens instead?

A warning is displayed:
`[0125/075246:WARNING:avc_decoder_configuration_record.cc(91)] Insufficient bits in bitstream for given AVC profile`

**Comment by agiudiceandrea** [comment]
@koln67, it looks like this warning has been introduced by you with PR https://github.com/shaka-project/shaka-packager/pull/799.

**Comment by cosmin** [comment]
The warning in #799 looks correct, this seems to be an issue with the file not being spec compliant, rather than an issue with the packager.
