### ISSUE TITLE
How to use shaka packager from go lang?

### ISSUE THREAD

**Issue by acris5** [shaka-project/shaka-packager#1333]
We have a large distributed system with workers in the go language. Is there any way to run the packager library not only from cpp?

**Comment by joeyparrish** [comment]
I have no expertise in go whatsoever.  But whatever interface exists to call foreign code (other languages) from go could likely be used to interface to Shaka Packager as a library.  In other languages where I have done similar things, you end up writing some code in C that interfaces between the two (external library & go) and translates data and function calls back and forth.
