### ISSUE TITLE
Deploying version 3.0.0

### ISSUE THREAD

**Issue by Jason239** [shaka-project/shaka-packager#1334]
AFAIK the 3.0.0 version of MR is blocked in progress, is there anything going on with that?
I'm waiting to use the [CMake build version](https://github.com/shaka-project/shaka-packager/projects/1#card-83555990) and wondering when this will be merged into the main branch..

**Comment by joeyparrish** [comment]
https://github.com/shaka-project/shaka-packager/pull/1312 has a list of issues/PRs that we intend to close before releasing v3.0.0.  You can follow along on our progress there.  @cosmin and I are both working on this process.  When #1312 is merged, an automated release of v3.0.0 will be triggered.

Thanks!
