### ISSUE TITLE
Queries on: Fixed position and style formatting for EBU-TT-D subtitles

### ISSUE THREAD

**Issue by Brainiarc7** [shaka-project/shaka-packager#1335]
## System info
**Operating System**: Ubuntu 22.04
**Shaka Packager Version**: main, git tip

## Issue and steps to reproduce the problem:

This is a query on the current state of Fixed position and style formatting for EBU-TT-D subtitles in shaka-packager.
As highlighted on [this](https://github.com/shaka-project/shaka-packager/pull/1181) PR, EBU Teletext input following Level 1.5 of the core specification ETSI EN 300 706 V1.2.1 (2003-04) and webvtt in MP4 segments output are implemented. This works well, as tested.

However, fixed position and style formatting for the same aren't implemented (yet), which raises two questions:

1. Can this be extended to [match what Amazon's Medialive implementation](https://docs.aws.amazon.com/medialive/latest/ug/ebut-tt-font-styles.html) achieves? 

2. Is such a feature within the scope of a downstream packager such as Shaka?

**Comment by tobbee** [comment]
I'm working on adding vertical positioning, approximative alignment (calculated from text positions to be left, center, and right) as well as text color. Should hopefully have a PR before the end of the month (March 2024).

**Comment by cosmin** [comment]
Closed by #1384
