### ISSUE TITLE
CMake version on arm64 workers is too old

### ISSUE THREAD

**Issue by cosmin** [shaka-project/shaka-packager#1345]
arm64 tests are failing with 

![image](https://github.com/shaka-project/shaka-packager/assets/1358/6ba92426-4abd-4eb1-bdc3-b1f70c684fa7)

**Comment by joeyparrish** [comment]
I thought this was fixed by the final version of https://github.com/shaka-project/shaka-packager/pull/1343.  Can you show me a CI run where it is failing after that point?

**Comment by joeyparrish** [comment]
The latest run of the 3.0.0 PR looks to be passing that point: https://github.com/shaka-project/shaka-packager/actions/runs/7911155227/job/21594894574?pr=1312

**Comment by cosmin** [comment]
It failed on #1303 let me rebase it and try again

**Comment by cosmin** [comment]
Rebasing to latest main fixed the issue
