### ISSUE TITLE
Shaka packager design in document

### ISSUE THREAD

**Issue by Jason239** [shaka-project/shaka-packager#1388]
Now I can't see the architecture diagram in the Shaka packager documentation, is there anywhere else I can see it?
https://shaka-project.github.io/shaka-packager/html/design.html#architecture-diagram

**Comment by cosmin** [comment]
@joeyparrish do you know how the documentation is being generated? It doesn't seem to be picking up the embedded graphviz elements.

**Comment by cosmin** [comment]
here is what it ought to look like if the graphviz was parsed correctly, based on the embeded graphviz in `docs/source/design.rst`

![Screenshot 2024-04-24 at 5 23 16 PM](https://github.com/shaka-project/shaka-packager/assets/1358/cc4a6252-e08d-46d6-85ba-7211f2d1617b)
![Screenshot 2024-04-24 at 5 22 37 PM](https://github.com/shaka-project/shaka-packager/assets/1358/3ae57a73-a44f-4a39-9436-76ede165af3d)
![Screenshot 2024-04-24 at 5 22 55 PM](https://github.com/shaka-project/shaka-packager/assets/1358/d1e5657d-1429-4176-9aec-044a137d5a07)

**Comment by joeyparrish** [comment]
It's possible we broke something in the overhaul of the build system.  Maybe there was some plugin or config for doxygen or sphinx that no longer works.
