### ISSUE TITLE
helpxml removed?

### ISSUE THREAD

**Issue by nbilyk** [shaka-project/shaka-packager#1405]
The option --helpxml seems to be removed somewhere after 2.6.1. I don't see a mention in the changelog that it was deprecated. I found it useful when generating a node API for shaka packager. Was this intentional?

**Comment by cosmin** [comment]
This unfortunately is a side effect of the move from gflags to abseil flags in 3.0. 

`--helpxml` was provided by gflags but there is no such thing in the abseil flags library, at least currently.
