### ISSUE TITLE
playing cathup 

### ISSUE THREAD

**Issue by Prathik9** [shaka-project/shaka-packager#1412]
its not an issue, but question from my side , how to play the particular time ranged cathup from my catchup stored.
means if i stored 24 hrs catch up and want to pack and stream only video from 13hr to 14hr , how do do it?

http://localhost/live_stream/multi_audio/manifest.mpd?begin=20181010T044000&end=20181010T052000, it is not working as expected.

please give me some feedback or solution.

**Comment by cosmin** [comment]
If you want the MPD to return only a subset of the segments based on parameters you would need to implement this at the server side layer, or use some media server that implements this.

**Comment by Prathik9** [comment]
> If you want the MPD to return only a subset of the segments based on parameters you would need to implement this at the server side layer, or use some media server that implements this.

yes @cosmin  but question how to identify the those segments , at present we identify segment based on $Number$ and $Time$ , then how to filter only those required timestamp segment , to deliver epg like feature over countries.
