### ISSUE TITLE
Add Missing Dash Roles to RoleFromString function

### ISSUE THREAD

**Issue by Johmpa** [shaka-project/shaka-packager#1418]
## System info
**Operating System**: macOS 14.5
**Shaka Packager Version**: 3.2.0

## Issue and steps to reproduce the problem
As issue https://github.com/shaka-project/shaka-packager/pull/1390 identified, several Dash roles in the specification were missing. These were added and included in the 3.1.0 release. 

However, many of the possible roles are not present in the RoleFromString function in period.cc, resulting in a failed packaging since the roles cannot be recognized. 

The following roles appear to be missing from the function:
- karaoke
- sign
- metadata
- enhanced-audio-intelligibility
- emergency
- easyreader

**Packager Command**: 
```
~/Movies/videodev/packager-test/source/shaka-packager/build/packager/packager \
in=avc1080.mp4,stream=audio,output=audio.mp4,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH,dash_roles=karaoke \
 in=avc1080.mp4,stream=video,output=avc.mp4,playlist_name=avc.m3u8,iframe_playlist_name=avc_iframe.m3u8 \
 --hls_master_playlist_output main.m3u8 \
 --mpd_output main.mpd
```

What is the expected result?
A successful packaging with the role "Karaoke" assigned.

What happens instead?
`code: 139, [0813/160352:ERROR:period.cc(208)] Unrecognized role 'karaoke'`

**Comment by joeyparrish** [comment]
Closed in #1419
