### ISSUE TITLE
how to install Shaka-Packager on ubuntu24.04.1 LTS

### ISSUE THREAD

**Issue by nntvcloud** [shaka-project/shaka-packager#1448]
I would like to know how to install Shaka-Packager on ubuntu24.04.1 LTS. I needed a complete procedure, and I looked at the online practice, but it didn't work.
cmake version 3.30.5
git version 2.34.1
ninja version 1.10.1

**Comment by joeyparrish** [comment]
If you just want a binary, you can download one from the releases page.  https://github.com/shaka-project/shaka-packager/releases

If you want to use Docker to isolate Shaka Packager from your host, you can use our official images.  https://hub.docker.com/r/google/shaka-packager

If you want to build it from source, follow the instructions in the docs.  https://shaka-project.github.io/shaka-packager/html/build_instructions.html

If the build instructions in the docs are too difficult to understand, please tell us what is confusing and we will improve the docs.

If the build instructions in the docs don't work for you, please give full details of the commands you ran and their full output, so we can understand the problem and help you solve it.

Thanks!

**Comment by nntvcloud** [comment]
![QQ图片20241111205119](https://github.com/user-attachments/assets/cdda017f-8d6b-4e9b-ad29-0604e439a97d)
20:50:32.537 ERROR: shaka-packager not found!
Based on the question in the picture, which one do I need to choose:
binary or Docker shaka packager and source

**Comment by joeyparrish** [comment]
Based on the screenshot, I have no idea what frontend tool you are using.  That output is not familiar to me.  I don't know what it is or how it expects to access Shaka Packager.  The tool you are using is not written or maintained by this group.  You should refer to the documentation for that tool, whatever it is.
