### ISSUE TITLE
error while fetching PTS/DTS of the .m4s

### ISSUE THREAD

**Issue by Prathik9** [shaka-project/shaka-packager#1451]
for DVR I used ffmpeg to fetch the PTS detail from saved segments by shaka-packager, for proper synchronization for the saved segments from live, while doing this I got the error.
Is there any method for properly synchronizing video and audio segments and then creating one custom manifest to deliver those?

Below Is the ffmpegs ffprobe cmd .

Plz help me to solve this

ffprobe -v error -select_streams v:0 -show_entries frame=pts_time -of csv=p=0 video_1.m4s

[mov,mp4,m4a,3gp,3g2,mj2 @ 00000188baa37140] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000188baa37140] error reading header
video_1.m4s: Invalid data found when processing input

**Comment by joeyparrish** [comment]
If that's a video segment, you will need the init segment as well.  When we do fragmented mp4 for streaming (DASH or HLS), the init segment has certain boxes describing tracks, codecs, other metadata.  If you try to feed ffmpeg one or more media segments without an init segment, it will not be able to understand it.

If you have the init segment (say, `video_init.mp4`), you can concatenate it with the media segment to get something ffmpeg can understand:

```sh
# Include as many media segments as you like
cat video_init.mp4 video_1.m4s > video.mp4

ffprobe -v error -select_streams v:0 -show_entries frame=pts_time -of csv=p=0 video.mp4
```

**Comment by joeyparrish** [comment]
You showed me what I believe is ffprobe failing to read a media segment.  I'm explaining that a media segment is not enough.  You also need the init segment.  If you concatenate them together (init + media), you get a file ffprobe can read.

The media segment has a timestamp, but the timestamp is in timescale units.  The timescale is in the init segment.  You can't interpret a media segment timestamp without the timescale.  For example, if the timestamp is `180,000`, and the timescale is `90,000`, then the timestamp is 2 seconds.

That's just how fragmented MP4 works.  If that's inconvenient, there's nothing we can do about it.  It's an industry standard that we didn't invent.

**Comment by Prathik9** [comment]
Thank you for your reply @joeyparrish I am a beginner so  I asked some of the questions, Thank you for the info
