### ISSUE TITLE
Can't install the Shaka Packager on macOS

### ISSUE THREAD

**Issue by Calushikid** [shaka-project/shaka-packager#1455]
I’m having a problem using the Shaka Packager on my system. I’m on macOS and i’ve been trying to use the most recent prebuilt release. But whenever I try to use it in Terminal with another tool that I have, it shows me an error that says that the permission was denied. It says that it doesn't have access to my home directory. 

I have tried by opening the file manually which leads to my Mac system saying that it couldn't check if it had anything malicious. So, I gave it permission manually in the Security section in the System Preferences. But it still won't work with my command in Terminal. Could anyone help me out with this?

**Comment by joeyparrish** [comment]
It sounds like you have a general permissions issue.  If you aren't familiar with permissions on the filesystem, you should read up on that. 

A file you download will never be marked executable by default.  Try `chmod +x path/to/packager` in the Terminal to make it executable. 

If that's not the issue, you need to give much more detail to get help from the community.  For example, show us the exact command you ran, and their exact output.
