### ISSUE TITLE
No equivalent 3-letter language code

### ISSUE THREAD

**Issue by atadzan** [shaka-project/shaka-packager#1457]
## System info
**Operating System**: Docker image alpine:3.18
**Shaka Packager Version**: v3.3.0

## Issue and steps to reproduce the problem

**Packager Command**:
```
/usr/local/bin/packager in=tmp/35ad6424-23c5-4a00-a2a9-c39c41bb0aa1.mp4,stream=1,segment_template=tmp/audio/iw/$Number$.aac,playlist_name=tmp/audio/iw/audio.m3u8,hls_group_id=audio,hls_name=,language=iw in=tmp/d483d2b0-635c-438e-8b65-2ccb35931585.mp4,stream=video,segment_template=tmp/480p/$Number$.ts,playlist_name=tmp/480p/playlist.m3u8 --segment_duration 4 --default_language iw --hls_master_playlist_output tmp/master.m3u8
```
Extra steps to reproduce the problem?
(1) Download [this](https://www.youtube.com/watch?v=Z57acavJjt4) video from youtube with default audio track
(2) Then try to transcode it with shaka-packager

What is the expected result?
**It is expected to be successfully transcoded**
What happens instead?
**It throws error like below**
```
packager_main.cc:624] Failed to initialize packager: 3 (INVALID_ARGUMENT): Unknown/invalid language specified: iw |  
language_utils.cc:136] No equivalent 3-letter language code for iw
```

I need help, please. Thanks in advance

**Comment by joeyparrish** [comment]
MP4s contain language metadata using 3-letter language codes only, so we map 2-letter codes to 3-letter codes to make this work.  It looks like our 2-letter-to-3-letter language code map is missing an entry.

The 3-letter code for Hebrew is "heb", so "iw" should map to "heb".

**Comment by joeyparrish** [comment]
I see "heb" mapped to "he", but not to the alternate 2-letter code "iw".

https://github.com/shaka-project/shaka-packager/blob/a26e6623d694fa4ca592e0b4594a01e4c23aa291/packager/media/base/language_utils.cc
