### ISSUE TITLE
(audio) track order in manifest.mpd

### ISSUE THREAD

**Issue by hariszukanovic** [shaka-project/shaka-packager#177]
It seems that the (audio) track order in output manifest is not controllable. The order in the manifest is used by many players to decide in which order to display the items in the audio selector UI control.

I tried specifying inputs in different order in the packager command line but I always get the same order in manifest.mpd

example:
shaka-packager
 'input=udp://238.100.100.2:6000,stream=video,stream_selector=0,init_segment=init-t11-video0.m4s,segment_template=chunk-t11-video0-$Number$.m4s,output_format=mp4'
 'input=udp://238.100.100.2:6000,stream=video,stream_selector=1,init_segment=init-t11-video1.m4s,segment_template=chunk-t11-video1-$Number$.m4s,output_format=mp4'
 'input=udp://238.100.100.2:6000,stream=video,stream_selector=2,init_segment=init-t11-video2.m4s,segment_template=chunk-t11-video2-$Number$.m4s,output_format=mp4'
 'input=udp://238.100.100.2:6000,stream=audio,language=mkd,stream_selector=4,init_segment=init-t11-audio-mkd.m4s,segment_template=chunk-t11-audio-mkd-$Number$.m4s,bandwidth=64000,output_format=mp4'
 'input=udp://238.100.100.2:6000,stream=audio,language=sqi,stream_selector=5,init_segment=init-t11-audio-sqi.m4s,segment_template=chunk-t11-audio-sqi-$Number$.m4s,bandwidth=64000,output_format=mp4'
 'input=udp://238.100.100.2:6000,stream=audio,language=srp,stream_selector=3,init_segment=init-t11-audio-srp.m4s,segment_template=chunk-t11-audio-srp-$Number$.m4s,bandwidth=64000,output_format=mp4'

outputs this manifest.mpd
http://pastebin.com/CUYZ6NDt

Myself, I would expect that audio stream be ordered like on the command line: mkd, sqi and srp.
If this is not expected behavior, perhaps it could be an acceptable suggestion for an improvement?

**Comment by kqyang** [comment]
Yes, that is something we need to improve. I will take this into consideration when doing Q1 2017 planning :)

**Comment by cgp1081** [comment]
@kqyang We're finding the order of audio tracks has impact on user experience.  

Roku for example, will default to English, but if * key is pressed, then menu closed, it will auto switch to Spanish if its listed first in MPD.  We can only control the experience through track order.

Currently the packager is listing Spanish first regardless or the order of arguments in the command

**Comment by kqyang** [comment]
@cgp1081 Do you set default_language? The AdaptationSet with the "default_language" will be tagged as "main" role, which signals to the player that it is the audio track to use.

**Comment by cgp1081** [comment]
@kqyang That works for default on startup, but whenever options menu is selected, the item thats first in the manifest will be selected.  When you close the menu without changing any selections, it will change the audio to whatever is first in the MPD.

**Comment by kqyang** [comment]
@cgp1081 It seems like a Roku bug to me. Have you talked to Roku about it?

If needed, we could sort the AdaptationSets by language (default first then order other languages alphabetically).

**Comment by cosmin** [comment]
The order is now specified by the order in the command line as of 3.0
