### ISSUE TITLE
Update manifest file with new segments

### ISSUE THREAD

**Issue by th3v0ice** [shaka-project/shaka-packager#289]
Is it possible to update the manifest file with the new data that is coming in? I have separate segments that are coming from some source and I want to run a packager on them and update the old manifest file with the new segments. I only get segments, i dont have a live source. 

So the flow is like this, a segment comes in, packager processes it and writes an mpd file. When the next segment comes in, packager processes it and updates the already created mpd file with the new segment and so on. 

Is this possible with the current latest release of the shaka-packager?

Thanks!

**Comment by rkuroiwa** [comment]
Unfortunately such scenario is not supported.

That said, If you are on Linux, you might be able to use pipes
https://google.github.io/shaka-packager/html/tutorials/ffmpeg_piping.html

1. Make a pipe
2. Run packager using pipe as input
3. Everytime you receive a segment cat it to the pipe.

**Comment by th3v0ice** [comment]
Thanks for the answer. Is it ever going to be supported?

**Comment by kqyang** [comment]
@th3v0ice We don't have plan to have direct support for that in the near term. Have you tried the solution described by @rkuroiwa? It should work as what you need.

**Comment by th3v0ice** [comment]
Well the data is not coming in at regular terms, is pipe really fit for this? It could be that next segment comes after few minutes.

**Comment by th3v0ice** [comment]
Yeah, i want the output stream to be continuous, one long stream. Time stamps are not continuous in the input, every segment for itself. :) However they could have continuous timestamps if packager is able to properly attach that information. I hope that I made everything clear. :)

**Comment by rkuroiwa** [comment]
I should've asked in the previous comment, but more questions.

Suppose the segments come in at times T1 T2 ... and the interval is not constant, and T0 is start of the first segment.
Are the segment durations the same as the interval? i.e. Is the first segment length T1 - T0, and for all the following segments T_n - T_n-1.

Phrasing the same question slightly differently.
Is this presenting the video as "live" or is it closer to "video-on-demand" but you just want to keep appending segments?

If former, piping solution might work.
Latter, we don't have a solution. We probably need Period support.

Also are the segments encoded using the same encoder configurations?

**Comment by th3v0ice** [comment]
No, the segments will have all similar duration, around x seconds, but the T1, T2, ... Tn are not the same. It could happen that the duration of x = T_n -1 - T_n, but is not always the case. 

I guess its kind of a live, where I append segments, but then again its maybe closer to the VOD if the segments are not coming at fixed intervals? Somewhere in between? :) I would like to present it as live. I am aware that it might stall the live video playback, but the T1..Tn are not controlled by me.

**Comment by vaage** [comment]
@th3v0ice, sorry for the silence on this issue. Before I try to get up to speed on the issue, is this still an issue for you?

**Comment by th3v0ice** [comment]
@vaage No problem! Thanks for responding :) As a matter of fact it still is an issue.

**Comment by vaage** [comment]
@th3v0ice I have read through the previous conversation and I want to make sure I understand the scenario correctly.

Are you looking for a command like:
```
packager 'in=new_segment.mp4,type=video,...' 'in=old_manifest.mpd' --mpd_output old-manifest.mpd
```

Where it would extract all the segments from the old manifest, merge it with the new segment(s), and then output to a new/same manifest?

**Comment by th3v0ice** [comment]
@vaage When You describe it like that, it sounds rather complicated, cant it just update the old manifest file and add one line that will include the new segment? If that is possible it would be a better solution in my humble opinion. 

But what You did describe is what I need.

**Comment by vaage** [comment]
@th3v0ice Under very specific circumstances, it would be simple, but most cases it would not be simple. For example, it the outputted MPD added encryption to the streams, we cannot just "add one line". We will need to encrypt the new video.

If the chunking in the outputted manifest was different from what the new video segment was, we could not just "add one line".

If there were multiple adaptations sets, cues, or any other permutations of other settings, it would not be possible to just "add one line".

This would be a fairly large enhancement. I will mark this as an enhancement and put it in our backlog for now.

**Comment by th3v0ice** [comment]
@vaage I am sorry if my lack of understanding in the issue caused some frustration. I only had best intentions, because my use case will at most use encryption of all the features that You described. Thanks for the help!

**Comment by vaage** [comment]
@th3v0ice, there is no frustrations. Just wanted to ensure that the issue reflected the full complexity of the feature so that when we pick this up later we don't need to re-investigate it.

**Comment by rkuroiwa** [comment]
Just a thought.
We shouldn't assume that this requires re-running a packager process.

There's [this](https://github.com/google/shaka-packager/blob/master/packager/file/public/buffer_callback_params.h) which allows appending data 
So unless the use case doesn't match, the packager could keep running. We just need to provide a way to pipe data into it.

Note that I'm not trying to say that this is a trivial task. In order to support this we have to put some thought into handling multiple media segments as input and signaling non-continuous segments to the manifest generator classes.

**Comment by vaage** [comment]
I was under the impression that pipes had already been discussed earlier in the thread, and were deemed not sufficient for the length of the delay between incoming data. Was I wrong?

**Comment by kqyang** [comment]
Actually @th3v0ice Do you have a few sample segments? It can help us determine if a simple piping could work. 

You can email it to shaka-packager-issues@google.com if the sample files cannot be exposed to public.

**Comment by th3v0ice** [comment]
Well @vaage is right, the problem here is that data could be coming in the following fashion:

S0 .... S1 ........ S2 .. S3 .. S4 ..... S5 .......... S6 ...

Where SX represents a segment number, and 1 dot represents 1 minute in time ( T ). The samples are really just a ts files of similar but not the same length and by that I mean they can be few seconds different. If  different segment length is the problem I can somehow take care of that. But I am more interested how to handle different time intervals between the segments. Thanks!

**Comment by FanFani4** [comment]
what is the right approach to create a mpeg-dash/hls stream from individual segments ? i am creating segments using MediaStreamRecorder.js, every ~5s a webm file is sent to server.
