### ISSUE TITLE
Support Single File TS for HLS

### ISSUE THREAD

**Issue by zshenker** [shaka-project/shaka-packager#291]
Support output of a single TS file for HLS media, instead of segmenting.
Use #EXT-X-BYTERANGE in the rendition manifests. May make sense to do this work at the same time as i-frame index playlists for HLS.

https://developer.apple.com/library/content/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-BYTE_RANGE_SUPPORT_FOR_SEGMENTS
@kqyang

**Comment by joeyparrish** [comment]
Closed by #934
