### ISSUE TITLE
generate HLS playlist for each stream (without --hls_master_playlist_output)

### ISSUE THREAD

**Issue by dulmandakh** [shaka-project/shaka-packager#296]
## System info
**Operating System**: Debian 9.2
**Shaka Packager Version**: v1.6.2-6b98f0d

## Issue and steps to reproduce the problem

**Packager Command**:
packager in=test-stream.mp4,stream=audio,out=out-stream.mp4,playlist_name=audio.m3u8

What is the expected result?
I expected that shaka packager would create HLS playlist for each stream.

What happens instead?
It don't create HLS playlist for each stream if --hls_master_playlist_output is not specified.

**Comment by kqyang** [comment]
--hls_master_playlist_output is required right now to generate the playlists. Any reason that you don't want the master playlist? Do you just want a single stream audio only playlist? (In which case, the master playlist isn't really useful)

**Comment by dulmandakh** [comment]
Yes, my use case is audio only. But it might be useful to generate playlist files even when --hls_master_playlist_output is not specified, and it might be useful for further processing (use cases).
