### ISSUE TITLE
Release via common distribution packagement management containers

### ISSUE THREAD

**Issue by bdurepo1** [shaka-project/shaka-packager#317]
Create Debian and Red Hat package management repository artifacts for releases. Releases should provide  RPM and DEB packages for users to install on their systems.

**Comment by kqyang** [comment]
@bdurepo1 That can be done in travis: https://github.com/google/shaka-packager/blob/master/.travis.yml. We'd love contributions if you know how to do it.

**Comment by bdurepo1** [comment]
How can I test my travis-ci script on your build system?

**Comment by kqyang** [comment]
You may fork the project and test it on your fork, which seems to be the simplest way.

**Comment by bdurepo1** [comment]
@kqyang my strategy will be to execute the RPM build from within a CentOS 7 Docker container. This of course will be launched using a Travis-CI build script.

**Comment by kqyang** [comment]
@bdurepo1 I am not familiar with RPM/DEB packages. Is there any problem with the default trusty environment in Travis-CI?

**Comment by bdurepo1** [comment]
@kqyang  No, the primary reason to package in this way is for configuration management compliance in an enterprise project. It is the standard way of distributing linux software. 

I understand that Google has its own internal processes. I have made some progress on generating RPM's in my fork but im not ready to issue a pull request yet
