### ISSUE TITLE
Support interlaced streams?

### ISSUE THREAD

**Issue by sammirata** [shaka-project/shaka-packager#349]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: packager version 2ba23e1-release

## Issue and steps to reproduce the problem

**Packager Command**: packager -dump_stream_info input=raw-00000695.ts.701293644850.ts

Extra steps to reproduce the problem?
(1) unzip the attached source file
(2) packager -dump_stream_info input=raw-00000695.ts.701293644850.ts

What is the expected result?
The analysis of the contents of the file

What happens instead?
[0311/094201:INFO:demuxer.cc(88)] Demuxer::Run() on file 'hls/ts/raw-00000695.ts.701293644850.ts'.
[0311/094201:INFO:demuxer.cc(160)] Initialize Demuxer for file 'hls/ts/raw-00000695.ts.701293644850.ts'.
[0311/094201:ERROR:packager_main.cc(463)] Packaging Error: 6 (END_OF_STREAM):

This file can be played by all players and analyzed fine with mediainfo and ffprobe. It comes from an HLS source (all segments give the same result).
[source.zip](https://github.com/google/shaka-packager/files/1800393/source.zip)

**Comment by kqyang** [comment]
field_pic_flag is set in video slice header, which indicates interlaced stream. We do not support interlaced streams right now. We'll need to evaluate what it takes to support interlaced streams and whether it can be supported.
