### ISSUE TITLE
startWithSAP & subsegmentStartsWithSAP attributes are not populated and this is not spec compliant

### ISSUE THREAD

**Issue by KameshDevarakonda** [shaka-project/shaka-packager#364]
## System info
**Operating System**: all
**Shaka Packager Version**: v2.0.2 (and previous versions)

## Issue and steps to reproduce the problem
When ShakaPackager generates DASH presentation, it doesn't indicate startWithSAP & subsegmentStartsWithSAP attributes either on AdaptationSet or Representation elements.

This is not spec compliant. From ISO/IEC 23009-1:2014(E), section 8.3 (on-demand profile) :
Representation elements with a @subsegmentStartsWithSAP value absent, zero or
greater than 3 may be ignored.

and 8.4 (live profile):
Representation elements with a @startWithSAP value (either supplied directly or inherited
from the containing) absent, zero or greater than 3 may be ignored.

**Comment by vaage** [comment]
@KameshDevarakonda Thank you for filing this issue. I have labelled it as "enhancement" as it will require new additions to the code base. I have put it under backlog as our current milestones are already full. @kqyang, could you look at scheduling this work?

**Comment by kqyang** [comment]
@koln67 Are you seeing this issue in your spec compliance check?

**Comment by koln67** [comment]
I'm not seeing this error with the conformance tool. Is there an example of input data and a packager command which generated this compliance error?

**Comment by XingzhaoYun** [comment]
For ec-3 and ac-4 track, these attributes are required and should be "1".

**Comment by cosmin** [comment]
Any progress on this issue by chance? To summarize the various SAP types in case it's helpful:

SAP type 1 should be used if for every fragment the first frame in decode order is also the first frame in presentation order (such as for fragments that start with I-frames)

SAP type 2 should be used when the first frame in decode order is not the first frame in presentation order, but the leading frames can be decoded (such as RADL in HEVC)

SAP type 3 should be used for open GOP encodings where the leading B-frames cannot be decoded and must be discarded (such as RASL for HEVC)

**Comment by kqyang** [comment]
We don't have resources to work on it ourselves. You are welcome to help us implement the support and send a PR to us.

**Comment by XingzhaoYun** [comment]
> We don't have resources to work on it ourselves. You are welcome to help us implement the support and send a PR to us.

Would it be possible to just contribute audio part?

**Comment by joeyparrish** [comment]
I don't see why not.

**Comment by XingzhaoYun** [comment]
Here is a solution only for audio https://github.com/shaka-project/shaka-packager/pull/1055
