### ISSUE TITLE
Support for Widevine encrypted UDP MPEGTS output

### ISSUE THREAD

**Issue by hariszukanovic** [shaka-project/shaka-packager#393]
Are there any plans on introducing support for widevine encrypted UDP output?

**Comment by kqyang** [comment]
We don't have a concrete plan right now, but we are looking into supporting it later this year or some time next year. I will update this issue once there is an update.

**Comment by hariszukanovic** [comment]
Any "standard" transport stream way you would be considering using to
deliver pssh to the player so it can fetch the license?

**Comment by kqyang** [comment]
Possibly following ISO/IEC 23009-1:2016 Common encryption of MPEG-2 transport streams, which defines a way of carrying PSSH in TS.

**Comment by karlg-arris** [comment]
@kqyang 
How about supporting Widevine CAS compliant output?
E.g inserting ECM in stream instead of PSSH

**Comment by kqyang** [comment]
@karlg-arris There is no plan to support Widevine CAS output right now in Shaka Packager. We will re-evaluate if there are a lot of requests for it.
