### ISSUE TITLE
Get the stream information

### ISSUE THREAD

**Issue by Jason239** [shaka-project/shaka-packager#466]
I know how I get stream information by using app.

`./packager.exe --dump_stream_info in=D:\contents\test.mp4`

But, can I get information from shaka :: media :: StreamInfo through the Shaka SDK?
I can only output it by passing parameters, but I can't get that information within my app.
I don't seem to be able to get the standard output because I don't use exe call from the outside.

Is there any other way to get stream info(e.g. stream type, track info etc) within my app?

**Comment by kqyang** [comment]
It is not exposed directly now. We are thinking updating the API to expose it in 2019. Added to 2019 Planning milestone.

**Comment by Jason239** [comment]
ah, I see.
So until that is updated, now I have to find another external way to analyze the input stream.
Thanks for your guidance.
