### ISSUE TITLE
Unable to parse webvtt input file

### ISSUE THREAD

**Issue by sammirata** [shaka-project/shaka-packager#511]
[hls_ts_test2-00035078.vtt.zip](https://github.com/google/shaka-packager/files/2608344/hls_ts_test2-00035078.vtt.zip)

## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: latest git (commit 061785285e1b746a2d2c3c9ea03e89786a73a1b0)

## Issue and steps to reproduce the problem
I am attaching the vtt file as well.

**Packager Command**:
"input=/data/public/group1/cacthuptv/test/ts/88547/hls_ts_test2-00035078.ts,stream_selector=0,init_segment=/data/public/group1/cacthuptv/test/ts/88547/hls_ts_test2-00035078-video-0-init.mp4,segment_template=/data/public/group1/cacthuptv/test/ts/88547/hls_m3u8_test2-video-0-$Time$.mp4 -segment_duration=1000 -fragment_duration=1000 -mp4_sequence_number_initial=885464 -mpd_output /data/public/group1/cacthuptv/test/m3u8/hls_ts_test2-00035078-video-0.mpd input=/data/public/group1/cacthuptv/test/ts/88547/hls_ts_test2-00035078.vtt,stream_selector=text,init_segment=/data/public/group1/cacthuptv/test/ts/88547/hls_ts_test2-00035078.init.mp4,segment_template=/data/public/group1/cacthuptv/test/ts/88547/hls_m3u8_test2-video-0-$Time$.mp4.vtt.m4s --enable_raw_key_encryption --keys label=:key_id=bdffdcba75c4465eb18619d58913f5d1:key=91305089cb40b898320362ab5f506394 --iv=bdffdcba75c4465eb18609d88943f5d1 --pssh 000000577073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED0000003708011210BDFFDCBA75C4465EB18609D58943F5D11A0B62757964726D6B65796F732210BDFFDCBA75C4465EB18609D58943F5D12A024844 --clear_lead 0 -allow_approximate_segment_timeline"

Here is the error log:
[1121/194329:INFO:demuxer.cc(88)] Demuxer::Run() on file '/data/public/group1/cacthuptv/test/ts/88547/hls_ts_test2-00035078.ts'.
[1121/194329:INFO:demuxer.cc(160)] Initialize Demuxer for file '/data/public/group1/cacthuptv/test/ts/88547/hls_ts_test2-00035078.ts'.
[1121/194329:ERROR:webvtt_parser.cc(176)] Failed to determine block classification:
 --- BLOCK START ---
    /* default values */
    ::cue {
      line-height: 5.33vh;
      font-size: 4.1vh;
      font-family: monospace;
      font-style: normal;
      font-weight: normal;
      background-color: black;
      color: white;
    }
    /* special cue parts */
    ::cue(c.transparent) {
      color: transparent;
    }
    /* need to set this before changing color, otherwise the color is lost */
    ::cue(c.semi-transparent) {
      color: rgba(0, 0, 0, 0.5);
    }
    /* need to set this before changing color, otherwise the color is lost */
    ::cue(c.opaque) {
      color: rgba(0, 0, 0, 1);
    }
    ::cue(c.blink) {
      text-decoration: blink;
    }
    ::cue(c.white) {
      color: white;
    }
    ::cue(c.red) {
      color: red;
    }
    ::cue(c.green) {
      color: lime;
    }
    ::cue(c.blue) {
      color: blue;
    }
    ::cue(c.cyan) {
      color: cyan;
    }
    ::cue(c.yellow) {
      color: yellow;
    }
    ::cue(c.magenta) {
      color: magenta;
    }
    ::cue(c.bg_transparent) {
      background-color: transparent;
    }
    /* need to set this before changing color, otherwise the color is lost */
    ::cue(c.bg_semi-transparent) {
      background-color: rgba(0, 0, 0, 0.5);
    }
    /* need to set this before changing color, otherwise the color is lost */
    ::cue(c.bg_opaque) {
      background-color: rgba(0, 0, 0, 1);
    }
    ::cue(c.bg_white) {
      background-color: white;
    }
    ::cue(c.bg_green) {
      background-color: lime;
    }
    ::cue(c.bg_blue) {
      background-color: blue;
    }
    ::cue(c.bg_cyan) {
      background-color: cyan;
    }
    ::cue(c.bg_red) {
      background-color: red;
    }
    ::cue(c.bg_yellow) {
      background-color: yellow;
    }
    ::cue(c.bg_magenta) {
      background-color: magenta;
    }
    ::cue(c.bg_black) {
      background-color: black;
    }
    /* Examples of combined colors */
    ::cue(c.bg_white.bg_semi-transparent) {
      background-color: rgba(255, 255, 255, 0.5);
    }
    ::cue(c.bg_green.bg_semi-transparent) {
      background-color: rgba(0, 256, 0, 0.5);
    }
    ::cue(c.bg_blue.bg_semi-transparent) {
      background-color: rgba(0, 0, 255, 0.5);
    }
    ::cue(c.bg_cyan.bg_semi-transparent) {
      background-color: rgba(0, 255, 255, 0.5);
    }
    ::cue(c.bg_red.bg_semi-transparent) {
      background-color: rgba(255, 0, 0, 0.5);
    }
    ::cue(c.bg_yellow.bg_semi-transparent) {
      background-color: rgba(255, 255, 0, 0.5);
    }
    ::cue(c.bg_magenta.bg_semi-transparent) {
      background-color: rgba(255, 0, 255, 0.5);
    }
    ::cue(c.bg_black.bg_semi-transparent) {
      background-color: rgba(0, 0, 0, 0.5);
    }
    ##
 --- BLOCK END ---
[1121/194329:ERROR:mp2t_media_parser.cc(312)] Ignore unsupported MPEG2TS stream type 0x86
[1121/194329:ERROR:packager_main.cc(519)] Packaging Error: 14 (INTERNAL_ERROR): Failed to parse WebVTT source. See log for details.

**Comment by kqyang** [comment]
@sammirata There are two WebVTT line terminators after `STYLE` in the vtt file, which is not compliant to the spec per https://www.w3.org/TR/webvtt1/#webvtt-style-block.

**Comment by sammirata** [comment]
I fixed the ccextractor source and retested ... Now, it stops a little later:

[1127/194425:ERROR:webvtt_parser.cc(176)] Failed to determine block classification:
 --- BLOCK START ---
    X-TIMESTAMP-MAP=MPEGTS:409712105, LOCAL 00:00:00.000
 --- BLOCK END ---

**Comment by kqyang** [comment]
@sammirata We do not support parsing WebVTT files with X-TIMESTAMP-MAP right now. We don't know if we should adjust the timestamp per the timestamp stated in `MPEGTS`. Or should we simple ignore the tag? Do you have any recommendations on how it should be processed?

**Comment by sammirata** [comment]
I think we should use this timestamp. In my case, it is going to match the one for the other tracks as all of them come from the same MPEG-TS segment (I am converting HLS to Dash, one segment at a time)

**Comment by sammirata** [comment]
Also, I do not think it is a good idea to kill the entire conversion process when the vtt parser fails. I would rather no captions but still have audio and video. Here is a suggestion:
diff --git a/packager/media/formats/webvtt/webvtt_parser.cc b/packager/media/formats/webvtt/webvtt_parser.cc
index 612ae21..18fe548 100644
--- a/packager/media/formats/webvtt/webvtt_parser.cc
+++ b/packager/media/formats/webvtt/webvtt_parser.cc
@@ -175,7 +175,9 @@ bool WebVttParser::Parse() {
 
     LOG(ERROR) << "Failed to determine block classification:\n"
                << BlockToString(block.data(), block.size());
-    return false;
+    // Ignore the unknown block
+    continue;
+    //return false;
   }

**Comment by kqyang** [comment]
@sammirata Thanks for the request for supporting X-TIMESTAMP-MAP. I have branched it to #515. Let us know if you are interested in implementing it!

**Comment by joeyparrish** [comment]
Closing due to the age of this conversation and the status labels on the issue.

If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
