### ISSUE TITLE
stream_selector=<number> and stream=<audio/video> options are synonyms with conflicting values.

### ISSUE THREAD

**Issue by BobCu** [shaka-project/shaka-packager#522]
I was using both the stream_selector=<number> and the stream=<audio/video> options, not realizing they were synonyms.  My input has 1 audio and 3 video streams for adaptive DASH + HLS.

Please throw an error when this option is repeated, no matter which name or value is used!

Going forward, it may be better to deprecate `stream=` in favor of separate options for `stream_selector=<int>` and `stream_type=<audio/video>`.  Permit them to be used together, with an error thrown only if the actual content of the numbered stream fails to match the stream type.

**Comment by kqyang** [comment]
> Please throw an error when this option is repeated, no matter which name or value is used!

Makes sense. Will address!

> Permit them to be used together, with an error thrown only if the actual content of the numbered stream fails to match the stream type.

I don't see a benefit of providing both in the same command. Can you clarify?

**Comment by BobCu** [comment]
Deprecate `stream=` in favor of separate `stream_selector=N` and `stream_type=video|audio`.  Using `stream_selector=audio` or `stream_type=3` would throw immediate value errors.

Personally, when input is from an MPEG-TS, I'd also like `stream_selector` values that are hex to be directly interpreted as PIDs, to eliminate all guesswork (and also eliminate the need to use `--dump_stream_info` to reverse-engineer an input stream I created in the first place!).

To respond to your question: A decision must be made to choose between parsing deep into the PIDs (SI tables, descriptors, NAL Units, etc.), or trusting a description given by the user.  However, when the parsing that ***is*** done conflicts with a tag provided by the user, and error should be thrown (or at least a warning logged).

Conversely, a user-provided tag could be used to ***disable*** lower-level real-time parsing, speeding up the overall packaging process.

This kind of descriptive tagging may also permit partially redundant options such as `hls_group_id=` to be deprecated.

**Comment by kqyang** [comment]
> Deprecate stream= in favor of separate stream_selector=N and stream_type=video|audio. Using stream_selector=audio or stream_type=3 would throw immediate value errors.

I don't see advantage of separating `stream` to `stream_selector` and `stream_type`. I am afraid that it may cause more confusions for some users. 

> I'd also like stream_selector values that are hex to be directly interpreted as PIDs

Agree that there are advantages of supporting that. However, PID is TS specific. We try to avoid any container specific information in generic options when possible.

> Conversely, a user-provided tag could be used to disable lower-level real-time parsing, speeding up the overall packaging process.

Can you elaborate?

> This kind of descriptive tagging may also permit partially redundant options such as hls_group_id= to be deprecated.

Can you clarify what you mean by this? Why is hls_group_id redundant?

**Comment by BobCu** [comment]
> > Deprecate stream= in favor of separate stream_selector=N and stream_type=video|audio. Using stream_selector=audio or stream_type=3 would throw immediate value errors.
> 
> I don't see advantage of separating `stream` to `stream_selector` and `stream_type`. I am afraid that it may cause more confusions for some users.

I don't see how reducing ambiguity can add confusion: It will cause change, but the change itself should be clear and simple, especially if the error message is concise and informative.

> > I'd also like stream_selector values that are hex to be directly interpreted as PIDs
> 
> Agree that there are advantages of supporting that. However, PID is TS specific. We try to avoid any container specific information in generic options when possible.

Then hex values could throw an error when a TS is not used.  At present there is no option that lets me manage by PID.  I don't really care if it's done by overloading `stream_selector` or not, just so there is a way it can be done at all.  That said, I suppose `--dump_stream_info` does manage. to get the job done...

> > Conversely, a user-provided tag could be used to disable lower-level real-time parsing, speeding up the overall packaging process.
> 
> Can you elaborate?

I've been working on an elaborate MPEG-TS parser that accepts all knows flavors used in the industry (especially the heavily hacked formats used by many satellite TV vendors), and when post-processing it pays great dividends to do as little parsing as possible, so great effort has been expended to parse only the minimum needed, and only when it's needed.  (Some of the streams are up to 1 Gbps on newer satellites!  Though the ones seen in the home are ~50 Mbps and easy to fully parse in real-time.)

I was guessing/hoping something similar would be beneficial to reduce the packager CPU load.

> > This kind of descriptive tagging may also permit partially redundant options such as hls_group_id= to be deprecated.
> 
> Can you clarify what you mean by this? Why is hls_group_id redundant?

Well, `hls_group_id` always seems to be set to `audio`, though I have no idea if it has other useful values.  And when there's only a single audio stream in the TS, `stream=` can also set to `audio`, which would make `hls_group_id` appear to be redundant.
