### ISSUE TITLE
Support WebM with multiple audios

### ISSUE THREAD

**Issue by Neeraja-hotstar** [shaka-project/shaka-packager#604]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem
Generate webm file for any multi audio content and try packaging with shaka

**Packager Command**:
packager in=SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm,stream=1,output=eng.webm in=SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm,stream=2,output=tel.webm in=SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm,stream=3,output=hin.webm in=SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm,stream=4,output=ben.webm in=SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm,stream=5,output=tam.webm in=SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm,stream=video,output=video.webm --default_language  eng --mpd_output master.mpd

The above SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm has 1 video and 5 audio tracks
ffprobe version n4.0-5-g0018cd0 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --disable-debug --disable-doc --enable-shared --enable-avresample --enable-gpl --enable-libx264 --enable-libfdk-aac --enable-nonfree --enable-openssl --enable-postproc --enable-small --enable-libvmaf --enable-version3 --extra-cflags=-I/include
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, matroska,webm, from 'SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm':
  Metadata:
    COMPATIBLE_BRANDS: qt
    MAJOR_BRAND     : qt
    MINOR_VERSION   : 512
    ENCODER         : Lavf58.12.100
  Duration: 00:05:00.01, start: -0.007000, bitrate: 352 kb/s
    Stream #0:0: Video: vp9, yuv420p(tv), 320x180, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      ENCODER         : Lavc58.18.100 libvpx-vp9
      DURATION        : 00:05:00.007000000
    Stream #0:1(eng): Audio: opus, 48000 Hz, mono, fltp (default)
    Metadata:
      HANDLER_NAME    : DataHandler
      ENCODER         : Lavc58.18.100 libopus
      DURATION        : 00:05:00.008000000
    Stream #0:2(tel): Audio: opus, 48000 Hz, mono, fltp (default)
    Metadata:
      HANDLER_NAME    : DataHandler
      ENCODER         : Lavc58.18.100 libopus
      DURATION        : 00:05:00.008000000
    Stream #0:3(hin): Audio: opus, 48000 Hz, mono, fltp (default)
    Metadata:
      HANDLER_NAME    : DataHandler
      ENCODER         : Lavc58.18.100 libopus
      DURATION        : 00:05:00.008000000
    Stream #0:4(ben): Audio: opus, 48000 Hz, mono, fltp (default)
    Metadata:
      HANDLER_NAME    : DataHandler
      ENCODER         : Lavc58.18.100 libopus
      DURATION        : 00:05:00.008000000
    Stream #0:5(tam): Audio: opus, 48000 Hz, mono, fltp (default)
    Metadata:
      HANDLER_NAME    : DataHandler
      ENCODER         : Lavc58.18.100 libopus
      DURATION        : 00:05:00.008000000

What is the expected result?
It should generate mpd with all the language tracks
What happens instead?
Multiple values for id 56aa specified
[0627/100456:ERROR:packager_main.cc(530)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file SLOPNGC_1_3--20190507215239675--PG--2012_180p_100_opus32k_vp9_common.webm
<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
This issue is related to #173. It seems like both issues can be addressed similarly.

**Comment by cosmin** [comment]
Merging to #173
