### ISSUE TITLE
VP9 webm FPS output not drop-frame

### ISSUE THREAD

**Issue by Sorqan** [shaka-project/shaka-packager#608]
## System info
**Operating System**: Windows 7 Pro SP1 64-bit
**Shaka Packager Version**: 2.3.0

## Issue and steps to reproduce the problem
My source media is encoded into VP9 webm files using ffmpeg and libvpx nothing really fancy with the encode but they are constant fps at 29.97 progressive and 23.976 progressive.
After going through the packager (separately, I'm not mixing frame rates), they are ending up as 30.033 fps and 24.000 fps respectively.

This is the below `%inputFile%_vp9_1920x1080.webm` MediaInfo:
```
General
Complete name                            : C:\Users\****vp9_1920x1080.webm
Format                                   : WebM
Format version                           : Version 2
File size                                : 13.0 MiB
Duration                                 : 34s 134ms
Overall bit rate                         : 3 200 Kbps
Writing application                      : Lavf58.20.100
Writing library                          : Lavf58.20.100 / Lavf58.20.100
TIMECODE                                 : 00:59:57:00

Video
ID                                       : 1
Format                                   : VP9
Codec ID                                 : V_VP9
Duration                                 : 34s 134ms
Bit rate                                 : 3 066 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (29970/1000) fps
Bits/(Pixel*Frame)                       : 0.049
Stream size                              : 12.5 MiB (96%)
Writing library                          : Lavc58.35.100 libvpx-vp9
Default                                  : Yes
Forced                                   : No
DURATION                                 : 00:00:34.134000000
```

This is the below output `vp9_1080p.webm` MediaInfo:

```
General
Complete name                            : C:\Users\*****vp9_1080p.webm
Format                                   : WebM
Format version                           : Version 4 / Version 2
File size                                : 13.0 MiB
Duration                                 : 34s 134ms
Overall bit rate                         : 3 200 Kbps
Writing application                      : https://github.com/google/shaka-packager version v2.3.0-5bf8ad5ed5-release
Writing library                          : libwebm-0.2.1.0

Video
ID                                       : 1
Format                                   : VP9
Codec ID                                 : V_VP9
Duration                                 : 34s 129ms
Bit rate                                 : 3 066 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.033 fps
Bits/(Pixel*Frame)                       : 0.049
Stream size                              : 12.5 MiB (96%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

23.976 source files are the same as above except the source is 23.976 fps and the packager output is 24.000 fps

H264 and H265 files do not have this issue, I'm packaging some at the same time with the same source frame rates and they are coming out with the correct fps at 29.970 and 23.976 respectively.

I'm running this with a batch script since I am on Windows.

**Packager Command**:
`shaka-packager.exe ^
in="%inputFile%_160k.mp4",stream=audio,output=stereo.mp4 ^
in="%inputFile%_h264_1280x720.mp4",stream=video,output=h264_720p.mp4 ^
in="%inputFile%_h264_1920x1080.mp4",stream=video,output=h264_1080p.mp4 ^
in="%inputFile%_h265_1280x720.mp4",stream=video,output=h265_720p.mp4 ^
in="%inputFile%_h265_1920x1080.mp4",stream=video,output=h265_1080p.mp4 ^
in="%inputFile%_vp9_1280x720.webm",stream=video,output=vp9_720p.webm ^
in="%inputFile%_vp9_1920x1080.webm",stream=video,output=vp9_1080p.webm ^
--segment_duration 6 ^
--fragment_duration 6 ^
--mpd_output %inputFile%.mpd`

I would assume that the vp9 files would end up with the same FPS as the source like the h264 and h265 files are doing but instead they are coming out as what seems to be non-drop-frame even though the source is drop-frame.

**Comment by kqyang** [comment]
@Sorqan Can you share a source webm file which we can use to re-produce the problem? You can email it to shaka-packager-issues@google.com if it cannot be shared publicly.

**Comment by Sorqan** [comment]
@kqyang Sorry, forgot to include some source media:

[2997_source_vp9_1280x720.zip](https://github.com/google/shaka-packager/files/3351634/2997_source_vp9_1280x720.zip)

**Comment by kqyang** [comment]
@Sorqan Yes, I can re-produce the problem with mediainfo. However, ffmpeg reports the correct frame rate. I suspect it is a problem with mediainfo.

**Comment by Sorqan** [comment]
@kqyang Right, I see what you're saying, ffprobe does in fact show 29.97, maybe it plays out fine and its just the metadata.
But one thing that I just noticed though is that the generated .mpd file also shows an unexpected frame rate numerator denominator and timescale:

`<AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="1000000/33000" subsegmentAlignment="true" par="16:9">
  <Representation id="0" bandwidth="3388977" codecs="vp09.00.31.08.00.02.02.02.00" mimeType="video/webm" sar="1:1" width="1280" height="720">
       <BaseURL>vp9_720p.mp4</BaseURL>
       <SegmentBase indexRange="310-344" timescale="1000000">`

Compared to the H265 in the same .mpd:

`<AdaptationSet id="1" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="30000/1001" par="16:9">
  <Representation id="1" bandwidth="4280241" codecs="hvc1.1.6.L93.90" mimeType="video/mp4" sar="1:1" width="1280" height="720">
       <BaseURL>h265_720p.mp4</BaseURL>
       <SegmentBase indexRange="3089-3144" timescale="30000">`

**Comment by kqyang** [comment]
@Sorqan Thanks for sharing the DASH manifest output. This does look like a problem. We will take a closer look.

**Comment by Sorqan** [comment]
@kqyang Any luck with a fix for this that you've found that I should try or that you need me to test?

**Comment by kqyang** [comment]
@Sorqan Not yet. Will keep you updated if we have a finding or fix.

**Comment by Sorqan** [comment]
@kqyang As another clue to the issue here, I just found that especially if I don't specify frame rate in the ffmpeg encode and then I pass that to the packager, it comes out as a variable frame rate even though the output of ffmpeg is constant.

Same numbers as above, 30.033 and 24.000 instead of the expected 29.970 and 23.976. It also appears that this does not affect the length of the video and there are even the same amount of frames as the source at least for a 30 second video.

**Comment by kqyang** [comment]
@Sorqan We don't actually change the sample duration so the frame rate should not change. We do record the sample duration in the frame info. There could be computational error. We will look into whether it is cause by that.

**Comment by Sorqan** [comment]
Just for a bit of extra data, I also just confirmed this issue is still present using the newest FFMPEG for encoding the VP9 using Shaka packager v2.5 on a Windows 10 computer as well.

In this test case, 23.976fps encoded VP9 .webm clips are changed to 24.000fps after packaging and the resultant .mpd shows frameRate="1000000/42000" (23.809fps?) instead of the expected 24000/1001 as the HEVC and AVC1 streams show in the same .mpd. Same sort of situation as above with 29.97 VP9 clips.

**Comment by cosmin** [comment]
Can you test this again with 3.2, there have been lots of changes since 2.5
