### ISSUE TITLE
Invalid amount of key IDs in Widevine PSSH data when protecting each stream using a different key

### ISSUE THREAD

**Issue by vladimir-kazakov** [shaka-project/shaka-packager#637]
When creating Widevine-protected content using different keys for each stream, I see that all key IDs are included into Widevine PSSH data of each stream. It seems to me that it's an incorrect behavior, since I'd expect only a single key ID in the PSSH data of a specific stream.

For example, I have a content consisting of 2 streams: audio and video. I want to protect the audio stream using the "all 1's" key ID and the "all A's" key. The video stream (SD quality) should be protected using the "all 2's" key ID and the "all B's" key. The command looks like:

```
packager \
  'in=In/aac-lc-128k.m4a,stream=audio,init_segment=Out/aac-lc-128k-init.mp4,segment_template=Out/aac-lc-128k-$Number$.mp4' \
  'in=In/h264-360p-750k.mp4,stream=video,init_segment=Out/h264-360p-750k-init.mp4,segment_template=Out/h264-360p-750k-$Number$.mp4' \
  --protection_scheme cbcs --clear_lead 0 --mp4_include_pssh_in_stream=false \
  --enable_raw_key_encryption --protection_systems Widevine \
  --keys 'label=AUDIO:key_id=11111111111111111111111111111111:key=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,label=SD:key_id=22222222222222222222222222222222:key=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB' \
  --segment_duration 2 --fragment_duration 2 \
  --generate_static_mpd --mpd_output Out/dash.mpd
```

Then, while inspecting PSSH boxes in `dash.mpd`, I see that they're the same for each stream, which is unexpected. Moreover, each PSSH box contains both key IDs in Widevine PSSH data. This is also unexpected.

I thought that maybe this happens because I didn't specify `drm_label` in the `in` field, but even after specifying DRM labels, the behavior is the same.

I'd expect to see different PSSH boxes for each stream. The PSSH box for the audio stream should have only one key ID (all 1's) in the Widevine PSSH data. The video stream should have only "all 2's".

I'm running Shaka Packager `c257113-release` on Ubuntu 18.04.3 inside a Docker container (`google/shaka-packager`, `b5ec0eef40bc`).

**Comment by kqyang** [comment]
@vladimir-kazakov This is intentional for performance reason. Widevine license server supports delivering multiple content keys in a single license. By bundling all the key_ids in the same pssh, the player will just need issue the license request once for all streams instead of once per key. This avoids extra round trips which would take time.

Let us know if it addresses your concern.

**Comment by vladimir-kazakov** [comment]
Okay, makes sense.

One more question. I accidentally used the same key ID for different tracks encrypted using different keys:
```
--keys 'label=AUDIO:key_id=11111111111111111111111111111111:key=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,label=SD:key_id=11111111111111111111111111111111:key=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
```
And as a result, I got a PSSH data with 2 same key IDs. Is it expected? I guess there is no point in duplicates. Moreover, perhaps the packager shouldn't continue processing content, if tracks are encrypted using different keys, but having the same key ID.

**Comment by kqyang** [comment]
@vladimir-kazakov No, that is not right. I agree that packager should reject the input: There should be an error checking for duplicated key-ids. Thanks for bringing this up.

**Comment by joeyparrish** [comment]
Closing due to the age of this conversation and the status labels on the issue.

If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
