### ISSUE TITLE
Understanding gaps reporting

### ISSUE THREAD

**Issue by jakubvojacek** [shaka-project/shaka-packager#658]
## System info
**Operating System**: debian
**Shaka Packager Version**: latest master

```
PID 256 Possible GAP at dts 642273840 with next sample at dts 650373840 (difference 8100000)
PID 257 Possible GAP at dts 642273840 with next sample at dts 650373840 (difference 8100000)
PID 258 Possible GAP at dts 642273840 with next sample at dts 650373840 (difference 8100000)
Representation (id=2,codec='mp4a.40.2',frequency=48000,language='por') Found a gap of size 8090880 > kRoundingErrorGrace (5). The new segment starts at 650358960 but the previous segment ends at 642268080.
Representation (id=1,codec='mp4a.40.2',frequency=48000,language='eng') Found a gap of size 8094720 > kRoundingErrorGrace (5). The new segment starts at 650366640 but the previous segment ends at 642271920.
```
The above is a log from packager. There are two types of warnings, one is about PIDs 256,257, 258 which are 3 different video profiles. The other two warnings are about gaps in audio. Are those somehow related? I would expect that the gaps would rather be in the video than in audio (as the bandwidth of audio is so much smaller). Is the reporting correct? Or why does packager show actual gaps in audio and at the same time it reports about possible gaps in video? 

Can you please explain how should I interpret this?

Thank you
Jakub

**Comment by kqyang** [comment]
@jakubvojacek Yes, they are related. They are actually referring to the same GAP from timestamp ~642273840 to ~650373840. 

I understand that the logging is a bit confusing, but it is related to the way the duration is calculated for audio and video.

For audio, the frame data is basically a collection of audio samples. The sample rate and the number of samples are encoded in the frame header, so we can calculate audio frame duration from just from the data in the frame header, without looking at the previous audio frame. If there are any GAPs in audio, it will be reported in Representation class later when generating the manifests.

For video, the video frame / sample is just a compressed static image, which does not have duration encoded in the frame data itself, so we calculate the duration from the difference to the timestamp of the previous video frame, see https://github.com/google/shaka-packager/blob/master/packager/media/formats/mp2t/es_parser_h26x.cc#L340. When packager sees an abnormal duration, it logs something similar to what you observed "PID xxx Possible GAP xxx".  The gap will not be reported again later in Representation class as there are not GAPs: there is just a sample with a very large duration.

@jakubvojacek Does that answer your question?

I am thinking about updating the logic to use the previous sample_duration if we see an extra large and abnormal duration, which can make the logging more consistent. What do you think?

**Comment by jakubvojacek** [comment]
Hello

so the GAP was present on all video profiles as well as audios, right? We are still battling with seeing gaps occasionally and we're unable to detect where the issue is. The setup is ffmpeg > udp > packager on one machine and packager is writing to network storage. CPU on transcoder seems fine, the network isn't overloaded. And all of a sudden, all channels from the transcoder start having these symptoms (except for radios that have tiny bandwidth). Anyway, that's out of the scope of this project.

> I am thinking about updating the logic to use the previous sample_duration if we see an extra large and abnormal duration, which can make the logging more consistent. What do you think?

Yes, that way it would be more understandable.

Thank you
Jakub

**Comment by weiyuefei** [comment]
@jakubvojacek hi, did you solve this issue? if you did, could you share your solution to this issue? Since we also meet this issue in our project, hope that get some help from you, thanks.

**Comment by jakubvojacek** [comment]
No, it seems to be caused by either insufficient network or write speed to the storage.
