### ISSUE TITLE
Feature request: LG's WebOs 3.0 compliant HLS stream

### ISSUE THREAD

**Issue by Nixon197** [shaka-project/shaka-packager#687]
Is there an option to produce audio and video in a single TS stream?

LG's WebOS 3.0 specs don't support audio-only TS streams as noted in http://webostv.developer.lge.com/common-page/faqs/streaming-http-live-streaming-hls-troubleshooting/

BR

**Comment by kqyang** [comment]
@Nixon197 Not right now. HLS-06 is already pretty old, the current HLS spec version is 23. Also, the FAQ in the link is provided in 2014, is it still valid?

**Comment by Nixon197** [comment]
@kqyang 

Hi

It seems that LG is pretty conservative about HLS version implementation.
According to this document http://webostv.developer.lge.com/discover/specifications/supported-media-formats/, even the newest version of WebOS - 4.5, is only supporting HLS version 5.

We tried with DASH also but no joy.
It would be great that Shaka could support older HLS versions.

BR

**Comment by cosmin** [comment]
There are no plans to support muxed HLS streams.
