### ISSUE TITLE
subtitles must start within the first 10 minutes, otherwise they get packaged incorrectly

### ISSUE THREAD

**Issue by godexsoft** [shaka-project/shaka-packager#697]
## System info
**Operating System**: Linux in Docker, Alpine
**Shaka Packager Version**: v2.3.0 in production

## Issue and steps to reproduce the problem
The problem appears only for a video that has very sparse subtitle usage. Specifically in the affected movie the first subtitle appears about **20 minutes into the movie**. This subtitle appears in **en_text/1.ts**. My understanding is that there is a window in which segments are kept in memory/disk and segments are synced to other streams (audio/video) so by the time 20 minutes pass 1.ts from the subtitles is long gone and hence there is no subtitle shown. I may be talking nonsense but that's my impression. 
What fixed the issue is adding a dummy subtitle at start of movie. As i understand adding it triggered generation of multiple empty segments and aligned everything correctly with the audio/video streams.

Also, it's noteworthy that only HLS was affected - MPD worked just fine.

**Packager Command** (using docker - google/shaka-packager:release-v2.3.0): 
	packager \			"input=/input/input.mp4,stream=audio,segment_template=audio/\$Number\$.ts,hls_group_id=audio,playlist_name=audio/audio.m3u8" \			"input=/input/input.mp4,stream=video,segment_template=video/\$Number\$.ts,hls_group_id=video,playlist_name=video/video.m3u8" \
		--enable_raw_key_encryption \
		--clear_lead 0 \
		--keys label=:key_id=KeyIDHex:key=KeyHex \
		--iv=IVHex \
		--protection_scheme cbcs \
		--pssh PSSHHex \
		--hls_playlist_type VOD \
		--hls_master_playlist_output "rootfile.m3u8"

Steps to reproduce:
(1) Package any video with subtitles that start from something like 20 minutes into the video
(2) Try playing the video with a compatible player (custom iOS player and videojs in safari in our case)

What is the expected result?
Subtitles show up correctly

What happens instead?
Subtitles don't show up but language selection in players work as expected

**Comment by kqyang** [comment]
@godexsoft This is a limitation in Shaka Packager as right now we only pad the time by 10 minutes: https://github.com/google/shaka-packager/blob/master/packager/packager.cc#L69. In standard production content, we do not expect to see a video without subtitles in the first 10 minutes.

A short term quick fix would be to increase the bias to 30 minutes. Do you think that will be sufficient for your use case?

**Comment by godexsoft** [comment]
Thanks for pointing that out @kqyang!

> A short term quick fix would be to increase the bias to 30 minutes. Do you think that will be sufficient for your use case?

That would fix the issue for this particular movie but just like you, I don't expect this to be an often use case if at all. Our solution was to just add the title of the movie as a subtitle somewhere around the first minutes of the video and that fixed the rest of it.
 
It's up to you but I would say better leave this for another day. Perhaps some day you can dedicate more time to find a better/proper solution for this. In the meantime we already know how to work around it. 

Thanks
