### ISSUE TITLE
Packager output video has missing data.

### ISSUE THREAD

**Issue by runetorgersen** [shaka-project/shaka-packager#700]
## System info
**Operating System**: Ubuntu 16.04 xenial
**Shaka Packager Version**: v2.3.0, master git branch f5f3f3abc57d14ad8daa7c79ceb7f70d7dc0764

## Issue and steps to reproduce the problem
We are trying to package content encoded with an Harmonix encoder.
Output results in video that has video glitches on the bottom few rows in picture.

Issue persists regardless of if packager uses TS or fragmented MP4 as storage.
All profiles are affected.

To me it looks like some bytes at the end of frames are dropped in the output.
All players tried (VLC, Chrome, Roku, FireTV) show the issue. VLC plays the input data just fine.

**Packager Command**:
Both of these commandlines generates output that demonstrate the problem:

`packager \
'in=cbs_lo.ts,stream=audio,init_segment=cbs/audio/init.mp4,stream=audio,segment_template=cbs/audio/$Number$.m4s,playlist_name=cbs/audio/main.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
'in=cbs_hi.ts,stream=video,init_segment=cbs/low/init.mp4,segment_template=cbs/low/$Number$.m4s,playlist_name=cbs/low/main.m3u8' \
'in=cbs_med.ts,stream=video,init_segment=cbs/med/init.mp4,segment_template=cbs/med/$Number$.m4s,playlist_name=cbs/med/main.m3u8' \
'in=cbs_lo.ts,stream=video,init_segment=cbs/high/init.mp4,segment_template=cbs/high/$Number$.m4s,playlist_name=cbs/high/main.m3u8' \
--segment_duration 8 --mpd_output cbs.mpd --hls_playlist_type EVENT --hls_master_playlist_output cbs.m3u8 --allow_approximate_segment_timeline --time_shift_buffer_depth 3635`
					

`packager \
'in=cbs_hi.ts,stream=audio,segment_template=cbs/audio/$Number$.aac,playlist_name=cbs/audio/main.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
'in=cbs_hi.ts,stream=video,segment_template=cbs/hi/$Number$.ts,playlist_name=cbs/hi/main.m3u8,iframe_playlist_name=cbs/hi/iframe.m3u8' \
--hls_master_playlist_output cbs.m3u8 --hls_playlist_type EVENT --segment_duration 10
`

The input files can be downloaded from:
[High Profile file](http://innostream2.innovsys.com/testhls/cbs_hi.ts)
[Medium Profile file](http://innostream2.innovsys.com/testhls/cbs_med.ts)
[Low Profile file](http://innostream2.innovsys.com/testhls/cbs_lo.ts)

FIles are 57MB, 26MB and 14MB (About 5 minutes of video, and are reasonably synced).

**Comment by runetorgersen** [comment]
After doing some comparisons with a in-house TS stream parser, the issue is that the shaka packager is dropping the last TS frame of the video.

Example is the file cbs_lo.ts.
The first sample in 1.m4s output file is 91 bytes short.
That is the 91 bytes in the last ts frame of the first full I-frame in cbs_lo.ts.
the last frame is at byte offset 123328. This is a front padded frame. The padding is done with Adaption field present, with a length of 92 bytes, and adaption field flags set to 0 (so no pts/dts). That leaves exactly 91 bytes left for payload.

Hexdump of the frame:

`00000000  47 00 20 30 5c 00 ff 79  df d2 f3 14 23 6d ca 5f`
`00000010  46 78 1e 5e 68 64 f9 c4  10 fc 12 d9 5f 80 5a 55`
`00000020  fb e1 89 20 b5 f1 3d 29  6a 30 a1 e2 1e 68 05 21`
`00000030  55 65 ed 26 5d e8 03 f6  3e e7 e2 15 7c 39 dd 80`
`00000040  05 f6 a4 27 48 14 dd 9f  af 70 99 36 53 39 a2 e1`
`00000050  4e 73 a2 6c b1 64 da fa  28 27 e3 bf 99 69 ab 87`
`00000060  d6 a7 83 25 58 35 31 b2  e7 02 1a 0b a5 26 52 27`
`00000070  96 9d 25 e6 6b ca e0 7f  9a e3 8b 30 80 dc 24 1d`
`00000080  cd 8c 9a 6a ee b8 8b 26  22 f1 41 19 1f 3a 26 bf`
`00000090  47 dd 97 05 9a 6b 8f 6a  46 4a 7a 74 ec 00 2d a3`
`000000a0  bf 38 e9 da 9a 96 fe 25  d7 32 f2 8c 12 5a 61 17`
`000000b0  ec fb d3 69 6f 98 57 e5  27 7c 46 c8`


missing video data starts at offset 0x0061

**Comment by kqyang** [comment]
@runetorgersen Thanks for the investigation. Are you seeing the same problem if you generate VOD playlist?

**Comment by runetorgersen** [comment]
Yes, I see the same issue with VOD playlist. Also get the same issue regardless of if output is TS or fMP4 files.

**Comment by kqyang** [comment]
If you can ffprobe on the output, does it give you the correct number of frames:

❯ ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 <file>

**Comment by runetorgersen** [comment]
I think so, but it does give a ton of errors parsing the output file(s) (when packaged as TS files, not sure how to use ffprobe on fragmented mp4 files).

ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 1.ts
[h264 @ 0x1af0160] error while decoding MB 75 44, bytestream -31
[h264 @ 0x1af0160] error while decoding MB 72 44, bytestream -29
[h264 @ 0x1af0160] error while decoding MB 67 44, bytestream -14
[h264 @ 0x1af0160] error while decoding MB 63 44, bytestream -10
[h264 @ 0x1af0160] error while decoding MB 71 44, bytestream -11
[h264 @ 0x1af0160] error while decoding MB 77 44, bytestream -37
[h264 @ 0x1af0160] error while decoding MB 66 44, bytestream -12
[h264 @ 0x1af0160] error while decoding MB 63 44, bytestream -8
[h264 @ 0x1af0160] error while decoding MB 63 44, bytestream -10
[h264 @ 0x1af0160] error while decoding MB 78 44, bytestream -6
[h264 @ 0x1bf62a0] error while decoding MB 75 44, bytestream -31
..
..
..
[h264 @ 0x1b147c0] error while decoding MB 71 44, bytestream -14
[h264 @ 0x1b28b00] error while decoding MB 69 44, bytestream -7
180
180

**Comment by cosmin** [comment]
ffmpeg reports errors parsing the input. While it is able to mask those issues we cannot expect packager to have the same resilience to corrupted inputs. If this is the output of a commercial encoder it might be worth triaging this with the encoder vendor, and ensuring that the files that encoder produces would pass a system and bitstream level validation.
