### ISSUE TITLE
ninja build command failing

### ISSUE THREAD

**Issue by ab5y** [shaka-project/shaka-packager#729]
## System info
**Operating System**: Windows 10 Home
**Shaka Packager Version**: commit a1dd82d

## Issue and steps to reproduce the problem
Follow all the steps for Windows OS given in the [build instructions](https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md). The ninja build command fails with an obscure error.

**Packager Command**:
`ninja -C out/Release_x64`

Extra steps to reproduce the problem?
None

What is the expected result?
Fully installed shaka-packager

What happens instead?
`ninja: build stopped: subcommand failed.`

![image](https://user-images.githubusercontent.com/4251453/76385132-ebbcae00-6386-11ea-8ce1-9c648bf9f178.png)
You can also find the above in a [gist](https://gist.github.com/ab5y/b3911dde9f7a5139e58f9f4e90a5cd70)

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
I believe it comes from Windows 10 SDK. Have you installed [Windows 10 SDK](https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md#windows-system-requirements)?

**Comment by ab5y** [comment]
@kqyang Yes, I remember installing as part of the VS2015 install. Upon checking my list of installed programs, I can see Windows SDK AddOn Version 10.1.0.0 is present.

**Comment by kqyang** [comment]
You may need to have the same exact SDK version. Can you check if you can solve the problem with this: https://magpcss.org/ceforum/viewtopic.php?f=6&t=14281?

**Comment by ab5y** [comment]
@kqyang Hey, I made a mistake in the earlier response. I had the correct version installed. I still got the 10.0.14393.795 from the microsoft site linked in the above page. It now prints a more verbose error I have saved in this [gist](https://gist.github.com/ab5y/18be00359047c5ec69f626ce08e94d92)

**Comment by kqyang** [comment]
@ab5y The new error is because there are two different Windows SDK versions on the system:

> c:\program files (x86)\windows kits\10\include\\**10.0.14393.0**\ucrt\corecrt.h(128): error C2953: '_CrtEnableIf<true,_Ty>': class template has already been defined
c:\program files (x86)\windows kits\10\include\\**10.0.10240.0**\ucrt\corecrt.h(125): note: see declaration of '_CrtEnableIf<true,_Ty>'

I don't know how that happens, but uninstalling version 10.0.10240.0 or removing it from the include path may help.

**Comment by ab5y** [comment]
@kqyang Umm, so I deleted the 10240 directory from the include  folder... and somehow the same errors persist?
They're also now becoming erratic. Some progress is being made as I see the overall number of items to be executed constantly reducing after every `ninja -C out/Release_x64` command. It executes about 10-15 things and then errors out. Stored the outputs [here](https://gist.github.com/ab5y/593b34a62187aaeb1e58aeaf0386580f) in case there might be any clues.

**Comment by kqyang** [comment]
> Some progress is being made as I see the overall number of items to be executed constantly reducing after every ninja -C out/Release_x64 command. It executes about 10-15 things and then errors out. 

That is normal with ninja as it does not compile the modules in the same order when it is invoked. The problem occurs when compiling `obj\base\win\base.win_util.obj`. 

From the log, the same problem still exists, the compile is still seeing two copies of SDKs.

```
c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt\corecrt.h(128): error C2953: '_CrtEnableIf<true,_Ty>': class template has already been defined
c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt.h(125): note: see declaration of '_CrtEnableIf<true,_Ty>'
```

Can you double check and make sure that 10240 has been removed?

Also, try removing `out/Release_x64` directory to force a clean compilation (need to run `gclient` again after removing the directory).

**Comment by ab5y** [comment]
Deleting the `out\Release_x64` directory did the trick! 
Also, might not be the proper place to mention this, but the 64 bit build instructions for Windows need slight tweaking. `set` and `&&` are essentially missing. Can I make the changes?

**Comment by kqyang** [comment]
@ab5y Glad to hear that. 

> Can I make the changes?

Yes, go ahead and submit a PR to us if there is anything that can be improved. Appreciated!

**Comment by joeyparrish** [comment]
@ab5y, there have been many changes to the build system since this was filed.  Is this still a problem for you?
