### ISSUE TITLE
Track numbers not compatible with ffprobe/no way to know stream order

### ISSUE THREAD

**Issue by totoCZ** [shaka-project/shaka-packager#809]
Hi,

I've been naively using 
` /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams`
to supply stream_selectors to shaka packager, but it seems to be wrong.

>    Stream #0:0[0xdd](cze): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 124 kb/s
    Stream #0:1[0xd3]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Stream #0:2[0xd4]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc

>"index": 0,
>"codec_name": "aac",

`/opt/shaka/packager --dump_stream_info`

>Found 5 stream(s).
>Stream [0] type: Video

Shaka always insists audio goes after video, while ffprobe puts it as index 0 here.

There is no programmatic way to access dump_stream_info, so I ended up running ffprobe twice, once for video and once for audio tracks and incrementing the counter manually.
Obviously I don't know if this order can change between files or software versions...

**Comment by TomHetmer** [comment]
Sample file
http://1737293223.rsc.cdn77.org/share/archive.ts

**Comment by cosmin** [comment]
The linked sample file is no longer accessible and the issue cannot be reproduced. If the issue still happens on latest version please reopen the issue with an attached sample.
