### ISSUE TITLE
Audio produced before video (PTS not aligned between audio and video segments)

### ISSUE THREAD

**Issue by hariszukanovic** [shaka-project/shaka-packager#853]
## System info
**Operating System**: Ubuntu 19.04
**Shaka Packager Version**: packager version v2.4.3-dd9870075f-release

## Issue and steps to reproduce the problem
When packaging the live stream transcoded by ffmpeg, segments of 10s length...

While the video segments seem all perfectly aligned in time, the audio segments seem to be produced far apart from all other video in time. Actually produced ahead in time. The difference varies by rather much, from 1-2 seconds to 20, but it is constant once the packaging has begun.
The first audio segment is always shorter than expected 10 seconds, perhaps that is expected?

All this seems to create problems for the player to start off quickly as it is downloading various segments seemingly in an attempt to find corresponding audio and video segments to start of with.

Since the difference is varying on different packager runs with the same input stream, I am inclined to suspect it might/should be resolved/resolvable in the packager. Perhaps by some means of discarding the excess audio ahead in time?
Or perhaps it is just a problem caused by the upstream transcoder?

**Packager Command**:
~/development/shaka-packager/src/out/Release/packager \
 "input=udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000,stream=video,stream_selector=1,bandwidth=500000,init_segment=dash/clear/init_v_r288p_${TS}.m4s,segment_template=dash/clear/chunk_v_r288p_\$Number\$_${TS}.m4s,output_format=mp4" \
 "input=udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000,stream=video,stream_selector=2,bandwidth=2000000,init_segment=dash/clear/init_v_r576p_${TS}.m4s,segment_template=dash/clear/chunk_v_r576p_\$Number\$_${TS}.m4s,output_format=mp4" \
 "input=udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000,stream=video,stream_selector=3,bandwidth=3000000,init_segment=dash/clear/init_v_r720p_${TS}.m4s,segment_template=dash/clear/chunk_v_r720p_\$Number\$_${TS}.m4s,output_format=mp4" \
 "input=udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000,stream=video,stream_selector=4,bandwidth=5000000,init_segment=dash/clear/init_v_r1080p_${TS}.m4s,segment_template=dash/clear/chunk_v_r1080p_\$Number\$_${TS}.m4s,output_format=mp4" \
 "input=udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000,stream=audio,language=eng,stream_selector=0,bandwidth=128000,init_segment=dash/clear/init_a_eng_${TS}.m4s,segment_template=dash/clear/chunk_a_eng_\$Number\$_${TS}.m4s,output_format=mp4" \
 --single_segment=false \
 --segment_duration 10 \
    --generate_dash_if_iop_compliant_mpd=1 \
    --minimum_update_period 10 \
    --time_shift_buffer_depth 60 \
    --hls_master_playlist_output clear_master.m3u8 \
    --hls_playlist_type LIVE \
    --mpd_output clear_manifest.mpd \
    --profile live

What is the expected result?
I expected that corresponding audio and video segments would be produced at roughly the same time and start with the same PTS (very near each other at least)

What happens instead?
On different runs of the packager, the corresponding audio and video segments (corresponding by their number) are produced with varying time difference in PTS between them, some times even up to 20 seconds of difference.
At the same time I can actually see audio segments are produced ahead in time by the same amount of difference in time.

Extra info:
I extracted PTS of first frame in segments. 
The listing format is:
a_eng_1 = audio english segment 1
v_r288p_1 = video 288p segment 1

All video segments are aligend, but audio in this example is near 15 seconds ahead

a_eng_1:pkt_pts_time=2639.888000
v_r288p_1:pkt_pts_time=2644.002667
v_r576p_1:pkt_pts_time=2644.002667
v_r720p_1:pkt_pts_time=2644.002667
v_r1080p_1:pkt_pts_time=2644.002667

a_eng_2:pkt_pts_time=2640.016000
v_r288p_2:pkt_pts_time=2654.002667
v_r576p_2:pkt_pts_time=2654.002667
v_r720p_2:pkt_pts_time=2654.002667
v_r1080p_2:pkt_pts_time=2654.002667

a_eng_3:pkt_pts_time=2650.000000
v_r288p_3:pkt_pts_time=2664.002667
v_r576p_3:pkt_pts_time=2664.002667
v_r720p_3:pkt_pts_time=2664.002667
v_r1080p_3:pkt_pts_time=2664.002667

a_eng_4:pkt_pts_time=2660.005333
v_r288p_4:pkt_pts_time=2674.002667
v_r576p_4:pkt_pts_time=2674.002667
v_r720p_4:pkt_pts_time=2674.002667
v_r1080p_4:pkt_pts_time=2674.002667

a_eng_5:pkt_pts_time=2670.010667
v_r288p_5:pkt_pts_time=2684.002667
v_r576p_5:pkt_pts_time=2684.002667
v_r720p_5:pkt_pts_time=2684.002667
v_r1080p_5:pkt_pts_time=2684.002667

..  it is all constant and repeating orderly afterwards

file creation times
-rw-rw-r-- 1 haris haris  158362 2020-10-12 12:48:52.588654502 +0200 chunk_a_eng_214_1602497602.m4s
-rw-rw-r-- 1 haris haris 2014207 2020-10-12 12:48:56.457701985 +0200 chunk_v_r576p_213_1602497602.m4s
-rw-rw-r-- 1 haris haris 2910186 2020-10-12 12:48:56.577703458 +0200 chunk_v_r720p_213_1602497602.m4s
-rw-rw-r-- 1 haris haris  576606 2020-10-12 12:48:56.633704145 +0200 chunk_v_r288p_213_1602497602.m4s
-rw-rw-r-- 1 haris haris 4721113 2020-10-12 12:48:56.687704808 +0200 chunk_v_r1080p_213_1602497602.m4s
-rw-rw-r-- 1 haris haris  158902 2020-10-12 12:49:02.669778222 +0200 chunk_a_eng_215_1602497602.m4s
-rw-rw-r-- 1 haris haris 2613236 2020-10-12 12:49:06.511825371 +0200 chunk_v_r576p_214_1602497602.m4s
-rw-rw-r-- 1 haris haris 3998914 2020-10-12 12:49:06.570826095 +0200 chunk_v_r720p_214_1602497602.m4s
-rw-rw-r-- 1 haris haris 6494107 2020-10-12 12:49:06.626826783 +0200 chunk_v_r1080p_214_1602497602.m4s
-rw-rw-r-- 1 haris haris  627982 2020-10-12 12:49:06.680827445 +0200 chunk_v_r288p_214_1602497602.m4s

..  also constant and repeating orderly all the time

While starting up the packager gives a lot of warnings of this kind
[1012/165322:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000'.
[1012/165322:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://239.100.101.1:6000?reuse=1&interface=0.0.0.0&timeout=5000000'.
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (24).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (24).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (24).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (24).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (25).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (25).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (25).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (25).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (26).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (26).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (26).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (26).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (27).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (27).
[1012/165323:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (27).
...
...
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (242).
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (242).
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (242).
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (242).
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (243).
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (243).
[1012/165331:WARNING:es_parser_h26x.cc(70)] Unusually large number of cached timestamps (243).

The longer the packager takes to start up, the longer the aduio/video PTS difference. It seems to be well correlated.

**Comment by hariszukanovic** [comment]
no triage still?

**Comment by hariszukanovic** [comment]
At all possible to get a comment on this?
Am I perhaps looking at something normal and expected?

**Comment by hariszukanovic** [comment]
@joeyparrish 
If triage in not needed.. maybe you could provide a short diagnosis or a comment on this?
I have seen (in other packager's output) the audio and video PTS pretty much aligned at the beginning of each chunk... 
Can you suggest where to intervene in the code to make this happen?

**Comment by joeyparrish** [comment]
Sorry, I don't know the answer.  My knowledge of the codebase is limited, as I inherited it and don't know where to find everything yet.  I have been working with members of the community on the build system and updating depdencies recently, and I haven't gotten that deep into the actual packaging logic.  We also don't have a dedicated team or anyone doing regular triage here.

I'm leaving this open in the hopes that someone else in the community can point you in the right direction.

**Comment by kqyang** [comment]
This is caused by different characteristics of the audio and video streams.

For the video stream, it waits until the key frame before start preparing the first media segment since the video samples couldn't be decoded and couldn't playback without the key frame; while for the audio stream, it starts preparing for the first media segment right away as every audio sample can be decoded independently without requiring another audio sample.

The simplest way to workaround the issue is to post process the generated manifest to remove the extra audio segments before the first video segment.

**Comment by hariszukanovic** [comment]
Thanx @kqyang. 
I really appreciate your advice on this...
To give a little newer date context on this issue

My use case is live streaming, so I believe it would not be easy to post process the generated manifest.

Additionally, I have this issue only with Shaka Player. 
AFAIU, Shaka player, starting from version 4.x, actually seems to have started expecting the audio and video streams PTS'es are near perfectly aligned at the beginning for each chunk (probably due to some optimizations regarding low-latency efforts)

Tried many other players and they do not have any problems with this "relatively small" amount of PTS misalignment between audio and video at the beginning of the chunks. The misalignment is actually in the range of the video GOP size.



**My attempt for the (simple) solution**
Since audio always precedes video (at least in my case that seems to be consequently so)... on packager startup... my idea was to discard audio frames of (only) the first audio chunk until audio PTS is as close as possible to the first video frame PTS (first keyframe in the first video chunk). 

In Mp2tMediaParser::EmitRemainingSamples() in packager/media/formats/mp2t/mp2t_media_parser.cc
I keep the all samples buffered until I find the first video PTS... then I discard all audio with PTS less than that.

The discarding itself actually seemed to work, as I got the PTS'es very well aligned for the first chunk... but the effect was not entirely good/usable because the duration of the audio chunk got messed up and already in the second chunk I got the misalignment right back again. 

Do you think this idea might at all be the way to do make it work? 
Perhaps I am missing something particular or even simple to additionally fix?



This is an example of how the PTS alignment looks like when I discard like described above..

**First chunk**
audio/video "perfectly" aligned 25315.451889 vs. 25315.460622
but duration is different, 4 s 565 ms vs. 6 s 0 ms

a_eng_1_1678192428.m4s
pkt_pts_time=25315.451889
Duration                                 : 4 s 565 ms

v_r576p_1_1678192428.m4s
pkt_pts=2278391456
pkt_pts_time=25315.460622
Duration                                 : 6 s 0 ms

v_r240p_1_1678192428.m4s
pkt_pts=2278391456
pkt_pts_time=25315.460622
Duration                                 : 6 s 0 ms

v_r480p_1_1678192428.m4s
pkt_pts=2278391456
pkt_pts_time=25315.460622
Duration                                 : 6 s 0 ms


**Second chunk**
audio/video again misaligned 25320.017222 vs. 25321.460622 (this seems to be exactly the same amount as I discarded in the first chunk)
but duration is back to normal (the target duration) of 10s


a_eng_2_1678192428.m4s
pkt_pts=2278801550
pkt_pts_time=25320.017222
Duration                                 : 9 s 984 ms

v_r576p_2_1678192428.m4s
pkt_pts=2278931456
pkt_pts_time=25321.460622
Duration                                 : 10 s 0 ms

v_r240p_2_1678192428.m4s
pkt_pts=2278931456
pkt_pts_time=25321.460622
Duration                                 : 10 s 0 ms

v_r480p_2_1678192428.m4s
pkt_pts=2278931456
pkt_pts_time=25321.460622
Duration                                 : 10 s 0 ms
