### ISSUE TITLE
Fails for SDR webm files that were converted from HDR

### ISSUE THREAD

**Issue by satazor** [shaka-project/shaka-packager#855]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v2.4.3

## Issue and steps to reproduce the problem

Packager fails when trying to package a SDR webm file that was encoded from a HDR one. The issue has to do with the fact that `ffmpeg` keeps the mastering data on the output file, which `packager` doesn't like.

**Packager Command**:
`packager in=test.webm --dump_stream_info`

Extra steps to reproduce the problem?
(1) `ffprobe test.webm` shows the file is in SDR (bt709), but has mastering data

```
Input #0, matroska,webm, from '.\test.webm':
  Metadata:
    ENCODER         : Lavf58.62.100
  Duration: 00:00:05.42, start: 0.000000, bitrate: 1922 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1240x720, SAR 32:31 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      ENCODER         : Lavc58.111.100 libvpx-vp9
      DURATION        : 00:00:05.422000000
    Side data:
      Mastering Display Metadata, has_primaries:1 has_luminance:1 r(0.6800,0.3200) g(0.2650,0.6900) b(0.1500 0.0600) wp(0.3127, 0.3290) min_luminance=0.005000, max_luminance=1000.000000
```

**What is the expected result?**

I would expect `packager` to not fail. I think it has to do with the way it's detecting if the file is HDR.
Please note that the above command runs fine for a SDR h264 mp4 file with the same mastering data. In fact, shaka removes the mastering metadata after transmuxing.

**What happens instead?**

The command fails.

[test.zip](https://github.com/google/shaka-packager/files/5385167/test.zip)

**Comment by cosmin** [comment]
In particular it's not going to like the min_luminance=0.005000, max_luminance=1000.000000 being set, which is the same issue as #810
