### ISSUE TITLE
Don't support I frame GOP  video?

### ISSUE THREAD

**Issue by zsmsky** [shaka-project/shaka-packager#864]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
packager version db5413e-release

## Issue and steps to reproduce the problem
Packager can encodec video,  that GOP's  first frame is IDR frame.
But if the GOP's first fram is I frame, it can't encodec well, it will look for IDR frame till the video is over.

For example:
Supported        GOP= IDR BB P BB P BB P BB P BB P BB
Unsupported    GOP= I BB P BB P BB P BB P BB P BB

**Packager Command**:

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
Support  this type video of GOP= I BB P BB P BB P BB P BB P BB

What happens instead?

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by zsmsky** [comment]
File:  shaka_packager\src\packager\media\formats\mp2t\es_parser_h264.cc
Fun:  bool EsParserH264::ProcessNalu(const Nalu& nalu, VideoSliceInfo* video_slice_info)

    case Nalu::H264_IDRSlice:
    case Nalu::H264_NonIDRSlice: {
      const bool is_key_frame = (nalu.type() == Nalu::H264_IDRSlice);
      DVLOG(LOG_LEVEL_ES) << "Nalu: slice IDR=" << is_key_frame;
      H264SliceHeader shdr;
      if (h264_parser_->ParseSliceHeader(nalu, &shdr) != H264Parser::kOk) {
        // Only accept an invalid SPS/PPS at the beginning when the stream
        // does not necessarily start with an SPS/PPS/IDR.
        if (last_video_decoder_config_)
          return false;
      } else {
        
        **//If I add this code, it can work OK.
        if(shdr.IsISlice() == 1)
        {
            is_key_frame =1;
        }**
        
        video_slice_info->valid = true;
        video_slice_info->is_key_frame = is_key_frame;
        video_slice_info->frame_num = shdr.frame_num;
        video_slice_info->pps_id = shdr.pic_parameter_set_id;
      }

**Comment by kqyang** [comment]
@zsmsky We expect all iframes to be an IDR frame. What is the rational for not using an IDR frame?

A separate question, does the packaged stream play successfully? If that is the case, you are welcomed to submit a PR to us with your fix.

**Comment by zsmsky** [comment]
> @zsmsky We expect all iframes to be an IDR frame. What is the rational for not using an IDR frame?
> 
> A separate question, does the packaged stream play successfully? If that is the case, you are welcomed to submit a PR to us with your fix.

GOP  has tow types :  open-GOP  and  close-GOP
In close-GOP,  I frame = IDR frame.  But in open-GOP, I frame != IDR frame.
Some videos do exist, the first frame is I-frame in the GOP。And I've met it.

**Comment by cosmin** [comment]
Per DASH-IF IOP segments must start with an IDR (SAP type 1 or 2). Open GOP encodings (SAP type 3) are not supported by packager.
