### ISSUE TITLE
cbcs packaged content does not work in Chrome on Android 9 and below.  

### ISSUE THREAD

**Issue by abdevnet** [shaka-project/shaka-packager#873]
## System info
**Operating System**: Android 9
**Shaka Packager Version**: c7312176

## Issue and steps to reproduce the problem

packager input=/tmp/2e5eaede-02e8-4b38-be8d-384f2701ca65/A49546_E2_WS_XX_XX/49546_en-US.mp4,stream=audio,drm_label=AUDIO,output=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/49546_en-US.mp4,language=en-US,playlist_name=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/audio-en-us-1.m3u8,hls_group_id=audio,hls_name="English" input=/tmp/2e5eaede-02e8-4b38-be8d-384f2701ca65/A49546_E2_WS_XX_XX/49546_240p_400kbps_en-US.mp4,stream=video,drm_label=SD,output=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/49546_240p_400kbps_en-US.mp4,playlist_name=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/videosd1.m3u8 input=/tmp/2e5eaede-02e8-4b38-be8d-384f2701ca65/A49546_E2_WS_XX_XX/49546_360p_800kbps_en-US.mp4,stream=video,drm_label=SD,output=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/49546_360p_800kbps_en-US.mp4,playlist_name=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/videosd2.m3u8 input=/tmp/2e5eaede-02e8-4b38-be8d-384f2701ca65/A49546_E2_WS_XX_XX/49546_480p_1500kbps_en-US.mp4,stream=video,drm_label=SD,output=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/49546_480p_1500kbps_en-US.mp4,playlist_name=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/videosd3.m3u8 input=/tmp/2e5eaede-02e8-4b38-be8d-384f2701ca65/A49546_E2_WS_XX_XX/49546_720p_2000kbps_en-US.mp4,stream=video,drm_label=HD,output=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/49546_720p_2000kbps_en-US.mp4,playlist_name=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/videohd4.m3u8 input=/tmp/2e5eaede-02e8-4b38-be8d-384f2701ca65/A49546_E2_WS_XX_XX/49546_720p_3000kbps_en-US.mp4,stream=video,drm_label=HD,output=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/49546_720p_3000kbps_en-US.mp4,playlist_name=/tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/videohd5.m3u8 --protection_scheme cbcs --enable_raw_key_encryption --keys label=AUDIO:key_id=C773E8CA4B1C26637DC52ECFC8A8EC9C:key=xx,label=SD:key_id=A69BEAFD658F9AB5A255D090129B0C7F:key=xx,label=HD:key_id=91CCDE6A3E5EDD6585A94634BD9B50EA:key=xx --iv 343D9BBCE3F5B053E2216CFC6279DECD --hls_key_uri=skd://KEYURIPLACEHOLDER --default_language en-US --pssh 0000007F7073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED0000005F1210C773E8CA4B1C26637DC52ECFC8A8EC9C1210A69BEAFD658F9AB5A255D090129B0C7F121091CCDE6A3E5EDD6585A94634BD9B50EA1A057377616E6B22204337373345384341344231433236363337444335324543464338413845433943 --segment_duration 3 --fragment_duration 3 --hls_master_playlist_output /tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/A49546_E2_WS_XX_XX.m3u8 --mpd_output /tmp/56160dc3-4c16-49f5-b099-1bf2c0bbc620/A49546_E2_WS_XX_XX.mpd

Extra steps to reproduce the problem?
play on Android 9

What is the expected result?
It Should Play.

What happens instead?
I get error CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=1050 append_window_start=0 append_window_end=733.608

<Please attach the input files or email to shaka-packager-issues@google.com.>

I removed the actual keys I used in the packager command above.  But,  I'm trying to package cbcs content.  This packaged content works on Android 10 in the chrome browser with our Widevine server but will not work in Android 9 and  below.  I can email the source files used if that helps.  I used pssh-box.py to generate the pssh header.  here is that command.

--widevine-system-id --content-id {hexifiedKey} --provider swank --key-id {audioKeyId} --key-id {sdKeyId} --key-id {hdKeyId} --hex

The items in brackets are substituted from variables of course.

**Comment by kqyang** [comment]
@abdevnet Thanks for the bug report. One question:

- Does it work in Chrome on Windows or ExoPlayer on Android?

**Comment by abdevnet** [comment]
It does work in Chrome on Windows.

**Comment by abdevnet** [comment]
The odd thing is the test content included in this url works on android 9 and it was packaged with Shaka packager -an older version. I’m trying to figure out what is different. 


https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd;license=https://proxy.uat.widevine.com/proxy?provider=widevine_test;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by kqyang** [comment]
Interesting. Which old version?

**Comment by abdevnet** [comment]
In the top of the .mpd file it has a comment indicating this version: 472fae2-release

**Comment by abdevnet** [comment]
[https://1drv.ms/u/s!AvUpMR3C3CXZhLgXP7fUQhKSyRqZ1A?e=cAjSBQ](url)  I've uploaded my source files here.

**Comment by abdevnet** [comment]
I have been able to playback CBCS packaged content on android 9 and 8.1 using the Bento packager.  So I'm curious what is different between the two packagers in how they are handling cbcs encryption.  

mp4dash --marlin --primetime --mpd-name=A49546_E2_WS_XX_XX.mpd  --encryption-key=451C479833C502FF65F7EBEF4A902C49:8EDED1593C3A2DFBD0D271072F0DE56F:14141604D9C290282103EF34739064CD --encryption-cenc-scheme=cbcs --hls --fairplay-key-uri=skd://451C479833C502FF65F7EBEF4A902C49:14141604D9C290282103EF34739064CD --widevine --widevine-header=provider:swank#content_id:3339394635393434364145423239373345343246463945443131313739364132  -o /tmp/out -f [type=audio,+language=en-US,+role=main]./49546_en-US.mp4  [type=video]./49546_240p_400kbps_en-US.mp4 [type=video]./49546_360p_800kbps_en-US.mp4 [type=video]./49546_480p_1500kbps_en-US.mp4 [type=video]./49546_720p_2000kbps_en-US.mp4 [type=video]./49546_720p_3000kbps_en-US.mp4  --no-split --profiles=on-demand

**Comment by kqyang** [comment]
@abdevnet Does it work for video or audio only manifest packaged by Shaka? It can help isolate whether it is caused by video or audio.

**Comment by cosmin** [comment]
This doesn't sound like a packager issue if it plays on modern browsers that are known to support Widevine CBCS, and only fails on old Android versions. In theory Android 7 and above should support Widevine with CBCS when going through ExoPlayer at least, not sure about support through Chrome on Android 8 or 9.
