### ISSUE TITLE
<Label> tag in mpd

### ISSUE THREAD

**Issue by Jason239** [shaka-project/shaka-packager#881]
Does Shaka packer support to set `<Label>` tag in DASH mpd ? 

Refer to page 35 of the link below.
https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf

**Comment by kqyang** [comment]
No, it is not supported right now. I'll mark it as a feature request. Let us know if you'd be interested in working on it yourself.

**Comment by Jason239** [comment]
Okay I'll try it

**Comment by cosmin** [comment]
done with #1175
