### ISSUE TITLE
HTTP stream input

### ISSUE THREAD

**Issue by Haerok** [shaka-project/shaka-packager#904]
## System info
**Operating System**: macOS Catalina
**Shaka Packager Version**: Master latest version

## Packager Error
[0224/151753:ERROR:packager_main.cc(556)] Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading https://[URL].mp4

Hi! I have a question about HTTP inputs : I've tried to find an issue (or related content) on this subject but couldn't find any : 
I have MP4 files (already transcoded) on a cloud storage (AWS S3 in my case) that I would like to use as input files. I'm using presign URLs for each files but shaka-packager fails to open them.

Is HTTPS input files supported? Is it something that I'm doing wrong? If it's not supported yet, is it considered as a future improvement?

I found the subject about HTTP upload but nothing on the input side.

Thank you in advance

**Comment by kqyang** [comment]
It is not supported right now. You are welcomed to help us implement it if you are interested. 

This is the function that needs to be modified: https://github.com/google/shaka-packager/blob/master/packager/file/http_file.cc#L140. Let me know if you have more questions.

**Comment by 89z** [comment]
Is this also the case for MPD files? I am trying to find a program for downloading and decrypting an MPD. I have the key.
