### ISSUE TITLE
HEVC in TS

### ISSUE THREAD

**Issue by synologic** [shaka-project/shaka-packager#915]
## System info
Debian 9.13
v2.4.3-dd98700-release

Reopen of #588.

HEVC in TS would be very useful when packaging for older devices which don't support fMP4, for example WebOS v3 does not support HLS version higher than 3 nor fMP4 but works just fine with HEVC in TS.

While the original issue mentions that Apple supports HEVC only in fMP4, there are other use cases where this is useful.

Would you reconsider implementing this, it would prevent packaging infrastructures being too complicated.

Thank you

**Comment by kqyang** [comment]
> While the original issue mentions that Apple supports HEVC only in fMP4, there are other use cases where this is useful.

There isn't a specification on how the HEVC should be encrypted and signaled in TS. Do you just want to package clear HEVC in TS?

**Comment by synologic** [comment]
What we're doing now is to package HEVC in TS and encrypt with AES-128 on the fly and craft the playlist with the proper key URL.
It would be great if this can also be done at the time of packaging. It works well for a lot of players, including Exoplayer :)

**Comment by kqyang** [comment]
Shaka packager does not support AES-128 encryption right now. See #776. 

I'll keep this issue open but in the keep in the backlog for now.

**Comment by cosmin** [comment]
Closing this since AES-128 encryption is covered by #776
