### ISSUE TITLE
A flag to remove the Shaka Packager comments from output manifests and playlists?

### ISSUE THREAD

**Issue by aradalvand** [shaka-project/shaka-packager#953]
When using Shaka Packager to generate either DASH or HLS content, in the output manifest file (`.mpd`) or playlist files (`.m3u8`), there's always a line like this:

![image](https://user-images.githubusercontent.com/26527405/121442438-ef335080-c9a0-11eb-99bc-5ca14905467b.png)

This just unnecessarily adds to the file size and makes the file a little ugly in general.

Nowhere in the documentation could I find anything that talked about this.

Would you please consider adding a simple flag (e.g. `--no-banner`) or something that can be used to omit this, in case somebody doesn't want it?

Thanks for all your efforts.

**Comment by kqyang** [comment]
It is a very useful information for debugging. We don't think the additional ~100 bytes affects the streaming, but we certainly understand your concern. 

There isn't a dynamic flag controlling the behavior right now. You can rebuild the binary to remove the version information if needed. You are also welcome to send a PR to us if you think it is helpful to add a flag to control the behavior.
