### ISSUE TITLE
`elst` and `mvhd` atoms reporting duration of 0 in output MP4's

### ISSUE THREAD

**Issue by nvincen** [shaka-project/shaka-packager#966]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
`AmazonLinux`

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
[f018c9a9bf6d936f3434ea32fb6a9ee42ae12b4b](https://github.com/google/shaka-packager/commit/f018c9a9bf6d936f3434ea32fb6a9ee42ae12b4b)

## Issue and steps to reproduce the problem

**Packager Command**:
```
docker run -it -v /tmp:/media local_registry:DigitalMusicShakaPackager-1.0-1618201405.1419096 packager "in=/media/TempMHA1.mp4,stream=audio,output=/media/output/TempMHA1.mp4" --fragment_duration 10 --segment_duration 10 --clear_lead 10 --v=-1 --generate_static_mpd --mpd_output /media/output/manifest-3.mpd
```

What is the expected result?
`/media/output/TempMHA1.mp4` should include accurate duration in `elst` and `mvhd` atoms

What happens instead?
Those atoms (`elst`, `mvhd`) are reporting duration of 0

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by cosmin** [comment]
This is expected for a fragment MP4.
