### ISSUE TITLE
No video(only audio) on Safari on MacOS(only M1 MacBook)

### ISSUE THREAD

**Issue by Jason239** [shaka-project/shaka-packager#974]
When packaging some content with Shaka packager in HLS(FPS DRM), there is an issue where only audio is normal and video does not play but only transparent screens are shown.
I think the content has something unusual. Can it be a problem because mdat is ahead of moov?
This issue occurs only in [this content](https://drive.google.com/file/d/1neMPGuKidxL0NkUjW5jvRt20uo3mcrK-/view?usp=sharing).

DRM : Yes(FPS)
Output : HLS(segmented ts + m3u8)
Occurrence Environment : Any player on Safari(on only M1 MacBook(Big Sur))

**Comment by Jason239** [comment]
Audio is normally decoded and played.

**Comment by Jason239** [comment]
> Can it be a problem because mdat is ahead of moov?

I tested, but it was not a problem.
I changed the order of moov metadata to priority and tried again, but it was still reproduced.

**Comment by cosmin** [comment]
What is the command line to reproduce this issue?
