### ISSUE TITLE
Support of Widevine encryption with Entitlement Keys ?

### ISSUE THREAD

**Issue by VinPiXe** [shaka-project/shaka-packager#983]
## System info
**Operating System**: <macOS Big Sur>
**Shaka Packager Version**: 2.5.1

## Issue and steps to reproduce the problem
I understand Shaka Packager supports Widevine encryption with Entitlement Keys but cannot find a relevant example in the documentation section 
https://google.github.io/shaka-packager/html/tutorials/widevine.html#examples) ?

If so, could someone possibly provide the details to encrypt a VOD content with entitlement keys ?

**Comment by mbolaris** [comment]
I too would like to know how to use Widevine Entitlement Keys with Shaka Packager.

**Comment by cosmin** [comment]
The command line option is simply --enable_entitlement_license, going to add this to the docs
