### ISSUE TITLE
PlayReady over HLS

### ISSUE THREAD

**Issue by deisenbacher01** [shaka-project/shaka-packager#984]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
Windows 2.5.1

## Issue and steps to reproduce the problem

Shaka does not seem to support Playready over HLS, it gives the error unknown system ID

What is the expected result?

What happens instead?
It should add the PR details to the .m3u8 as per

https://docs.microsoft.com/en-us/playready/packaging/mp4-based-formats-supported-by-playready-clients?tabs=case4

**Comment by joeyparrish** [comment]
Fixed in #1011
