### ISSUE TITLE
HLS / DASH support for forced subtitles

### ISSUE THREAD

**Issue by vish91** [shaka-project/shaka-packager#988]
Does shaka-packager support setting forces subtitles in HLS and DASH.  Mainly DASH ? 

In HLS it's the stream media tag `FORCED`
and in DASH its a ROLE `forced-subtitles`

https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/165

https://github.com/Dash-Industry-Forum/Ingest/issues/40

Based on the first issue it looks like Shaka-player and ExoPlayer do support it for HLS and DASH

**Comment by kqyang** [comment]
That is not supported right now.

To support DASH `forced-subtitles`, a new role needs to be added. You can look at other roles to see how to add a new role, e.g. https://github.com/google/shaka-packager/search?q=kRoleCommentary.

To support HLS `FORCED` media tag, a new stream descriptor needs to be added. You can checkout `hls_characteristics` to see how to add support for a new stream descriptor: https://github.com/google/shaka-packager/search?q=hls_characteristics. We may use the same stream descriptor tag to signal DASH `forced-subtitles` too.

@vish91 Do you want to work on it?

**Comment by raestrada95** [comment]
@kqyang i am also interested in this function it would be great if you could implement it

**Comment by vish91** [comment]
@kqyang  for DASH I understood and made progress. 
For HLS are you suggesting it should be a stream descriptor property like `hls_characteristics` and not a Media Playlist Tag property ? 
Thinking because I see `default` and `autoselect` being defined as `is_default` and `is_autoselect` in 
https://github.com/google/shaka-packager/blob/master/packager/hls/base/master_playlist.cc#L276
That will also help me decide what kind of data type I use if we decide to use it as a stream descriptor so like boolean vs enum string for YES/NO property values.

**Comment by kqyang** [comment]
Yes, it needs to be a stream descriptor property. The media playlist tag property is derived internally in the code.

I think you can define it as a boolean and parse it in the same way as `dash_only`: https://github.com/google/shaka-packager/blob/master/packager/app/stream_descriptor.cc#L224

**Comment by vish91** [comment]
@kqyang  gotcha and if its a stream descriptor. Does it still need to be declared or set after parsing it in stream_descriptor.cc ? Like how the hls_characterisctics after parsing are still being set in media_playlist.cc and hls_notify_muxer_listener. Trying to gauge where the actual conversion would happen from when it's parsed as bool in stream_descriptor to where the media_playlist is getting created. 
One more question: once we parse and define the FORCED flag as per spec we should also make sure that AUTOSELECT=YES always if the forced flag is set in the master_playlist.cc file ? Does that sound right ?

**Comment by kqyang** [comment]
> Does it still need to be declared or set after parsing it in stream_descriptor.cc ?

Yes, I suggest defining an accessor in media_playlist.h similar to characteristics() function.

> One more question: once we parse and define the FORCED flag as per spec we should also make sure that AUTOSELECT=YES always if the forced flag is set in the master_playlist.cc file ? Does that sound right ?

I don't think we should set AUTOSELECT to YES for FORCED subtitles.

**Comment by defagos** [comment]
> I don't think we should set AUTOSELECT to YES for FORCED subtitles.

According to rule 5.11 of the [HTTP Live Streaming (HLS) authoring specification for Apple devices](https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices) forced subtitles SHOULD always have `AUTOSELECT=YES`.
