### ISSUE TITLE
--protection_scheme  seems not work under  --enable_raw_key_encryption

### ISSUE THREAD

**Issue by liulihuaos** [shaka-project/shaka-packager#998]
## System info
**Operating System**: windows 8.1
**Shaka Packager Version**: v2.6.1

## Issue and steps to reproduce the problem
we use cenc cens cbc1 protection_scheme in enable_raw_key_encryption mode, but the encrypted result seems all the same
**Packager Command**:
packager-win-x64.exe "in=H:\8M.ts,stream=video,segment_template=H:\test7\$Number$.ts,playlist_name=H:\test7\main.m3u8,iframe_playlist_name=H:\test7\iframe.m3u8,drm_label=HD" --protection_scheme cenc --enable_raw_key_encryption --keys label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead --iv 1234567890abcdef --hls_master_playlist_output H:\test7\h264_master.m3u8

packager-win-x64.exe "in=H:\8M.ts,stream=video,segment_template=H:\test8\$Number$.ts,playlist_name=H:\test8\main.m3u8,iframe_playlist_name=H:\test8\iframe.m3u8,drm_label=HD" --protection_scheme cens --enable_raw_key_encryption --keys label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead --iv 1234567890abcdef --hls_master_playlist_output H:\test8\h264_master.m3u8

packager-win-x64.exe "in=H:\8M.ts,stream=video,segment_template=H:\test10\$Number$.ts,playlist_name=H:\test10\main.m3u8,iframe_playlist_name=H:\test10\iframe.m3u8,drm_label=HD" --enable_raw_key_encryption --protection_scheme cbc1 --keys label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead --iv 1234567890abcdef  --hls_master_playlist_output H:\test10\h264_master.m3u8
Extra steps to reproduce the problem?
(1)just use the cmd above
(2)

What is the expected result?
 encrypted results are defferent between cenc cens cbc1

What happens instead?
the encrypted result seems all the same

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by cosmin** [comment]
What do you mean the output is the same? I ran this using different protection schemes and the output is different and the correct protection scheme is signaled in the MPD.
